//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos
{
    using Google.GenAI.Gaos.Hooks;
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Errors;
    using Google.GenAI.Gaos.Utils;
    using Google.GenAI.Gaos.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    /// <summary>
    /// Gemini API: The Gemini Interactions API allows developers to build generative AI applications using Gemini models. Gemini is our most capable model, built from the ground up to be multimodal. It can generalize and seamlessly understand, operate across, and combine different types of information including language, images, audio, video, and code. You can use the Gemini API for use cases like reasoning across text and images, content generation, dialogue agents, summarization and classification systems, and more.
    /// </summary>
    public interface IGenAI
    {
        public IInteractions Interactions { get; }

        public IWebhooks Webhooks { get; }

        public IAgents Agents { get; }

        public ITriggers Triggers { get; }

        public IEnvironments Environments { get; }
    }

    /// <summary>
    /// Gemini API: The Gemini Interactions API allows developers to build generative AI applications using Gemini models. Gemini is our most capable model, built from the ground up to be multimodal. It can generalize and seamlessly understand, operate across, and combine different types of information including language, images, audio, video, and code. You can use the Gemini API for use cases like reasoning across text and images, content generation, dialogue agents, summarization and classification systems, and more.
    /// </summary>
    public class GenAI : IGenAI
    {
        /// <summary>
        /// The main SDK Configuration.
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }
        /// <summary>
        /// The Interactions sub-SDK.
        /// </summary>
        public IInteractions Interactions { get; private set; }
        /// <summary>
        /// The Webhooks sub-SDK.
        /// </summary>
        public IWebhooks Webhooks { get; private set; }
        /// <summary>
        /// The Agents sub-SDK.
        /// </summary>
        public IAgents Agents { get; private set; }
        /// <summary>
        /// The Triggers sub-SDK.
        /// </summary>
        public ITriggers Triggers { get; private set; }
        /// <summary>
        /// The Environments sub-SDK.
        /// </summary>
        public IEnvironments Environments { get; private set; }

        /// <summary>
        /// Initializes a new instance of the SDK based on a <see cref="SDKConfig"/> configuration object.
        /// </summary>
        /// <param name="config">The SDK configuration object.</param>
        public GenAI(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Interactions = new Interactions(SDKConfiguration);

            Webhooks = new Webhooks(SDKConfiguration);

            Agents = new Agents(SDKConfiguration);

            Triggers = new Triggers(SDKConfiguration);

            Environments = new Environments(SDKConfiguration);
        }

        /// <summary>
        /// Initializes a new instance of the SDK with optional configuration parameters.
        /// </summary>
        /// <param name="security">The security configuration to use for API requests. If provided, this will be used as a static security configuration.</param>
        /// <param name="securitySource">A function that returns the security configuration dynamically. This takes precedence over the static security parameter if both are provided.</param>
        /// <param name="apiVersion">Which version of the API to use.</param>
        /// <param name="userProject">Quota project header to send with Google GenAI API requests.</param>
        /// <param name="serverIndex">The index of the server to use from the predefined server list. Must be between 0 and the length of the server list. Defaults to 0 if not specified.</param>
        /// <param name="serverUrl">A custom server URL to use instead of the predefined server list. If provided with urlParams, the URL will be templated with the provided parameters.</param>
        /// <param name="urlParams">A dictionary of parameters to use for templating the serverUrl. Only used when serverUrl is provided.</param>
        /// <param name="client">A custom HTTP client implementation to use for making API requests. If not provided, the default GenAIHttpClient will be used.</param>
        /// <param name="retryConfig">Configuration for retry behavior when API requests fail. Defines retry strategies, backoff policies, and maximum retry attempts.</param>
        /// <exception cref="ArgumentOutOfRangeException">Invalid value provided for <paramref name="serverIndex"/>: must be between 0 (inclusive) and 1 (exclusive).</exception>
        /// <exception cref="ArgumentException">None of <paramref name="security"/> and <paramref name="securitySource"/> were provided.</exception>
        public GenAI(
            Google.GenAI.Gaos.Models.Components.Security? security = null,
            Func<Google.GenAI.Gaos.Models.Components.Security>? securitySource = null,
            string? apiVersion = null,
            string? userProject = null,
            int? serverIndex = null,
            string? serverUrl = null,
            Dictionary<string, string>? urlParams = null,
            IGenAIHttpClient? client = null,
            RetryConfig? retryConfig = null
        )
        {
            if (serverIndex != null)
            {
                if (serverIndex.Value < 0 || serverIndex.Value >= SDKConfig.ServerList.Length)
                {
                    throw new ArgumentOutOfRangeException($"Invalid server index {serverIndex}: must be between 0 (inclusive) and {SDKConfig.ServerList.Length} (exclusive).");
                }
            }

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<Google.GenAI.Gaos.Models.Components.Security>? _securitySource = null;

            if (securitySource != null)
            {
                _securitySource = securitySource;
            }
            else if (security != null)
            {
                _securitySource = () => security;
            }
            else
            {
                throw new ArgumentException("security and securitySource cannot both be null");
            }

            SDKConfiguration = new SDKConfig(client) {
                ApiVersion = apiVersion,
                UserProject = userProject,
                ServerIndex = serverIndex == null ? 0 : serverIndex.Value,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            InitHooks();

            Interactions = new Interactions(SDKConfiguration);

            Webhooks = new Webhooks(SDKConfiguration);

            Agents = new Agents(SDKConfiguration);

            Triggers = new Triggers(SDKConfiguration);

            Environments = new Environments(SDKConfiguration);
        }

        private void InitHooks()
        {
            SDKConfiguration = SDKConfiguration.Hooks.SDKInit(SDKConfiguration);
        }

        /// <summary>
        /// Builder class for constructing an instance of the SDK.
        /// </summary>
        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new GenAIHttpClient());

            public SDKBuilder()
            {
            }

            /// <summary>
            /// Overrides the default server by index.
            /// </summary>
            public SDKBuilder WithServerIndex(int serverIndex)
            {
                if (serverIndex < 0 || serverIndex >= SDKConfig.ServerList.Length)
                {
                    throw new ArgumentOutOfRangeException($"Invalid server index {serverIndex}: must be between 0 (inclusive) and {SDKConfig.ServerList.Length} (exclusive).");
                }
                _sdkConfig.ServerIndex = serverIndex;
                return this;
            }

            /// <summary>
            /// Overrides the default server URL for the SDK.
            /// </summary>
            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }
            /// <summary>
            /// Sets the ApiVersion global parameter for the SDK.
            /// </summary>
            public SDKBuilder WithApiVersion(string apiVersion)
            {
                _sdkConfig.ApiVersion = apiVersion;
                return this;
            }
            /// <summary>
            /// Sets the UserProject global parameter for the SDK.
            /// </summary>
            public SDKBuilder WithUserProject(string userProject)
            {
                _sdkConfig.UserProject = userProject;
                return this;
            }

            /// <summary>
            /// Sets the securitySource security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithSecuritySource(Func<Google.GenAI.Gaos.Models.Components.Security> securitySource)
            {
                _sdkConfig.SecuritySource = securitySource;
                return this;
            }

            /// <summary>
            /// Sets the security security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithSecurity(Google.GenAI.Gaos.Models.Components.Security security)
            {
                _sdkConfig.SecuritySource = () => security;
                return this;
            }

            /// <summary>
            /// Sets a custom HTTP client to be used by the SDK.
            /// </summary>
            public SDKBuilder WithClient(IGenAIHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            /// <summary>
            /// Sets the retry configuration for the SDK.
            /// </summary>
            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            /// <summary>
            /// Builds and returns the SDK instance.
            /// </summary>
            public GenAI Build()
            {
                if (_sdkConfig.SecuritySource == null)
                {
                    throw new ArgumentException("securitySource cannot be null. One of `Security` or `securitySource` needs to be defined.");
                }
                return new GenAI(_sdkConfig);
            }
        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}