//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Utils.Retries
{
    public class RetryConfig
    {
        /// <summary>
        /// Available retry strategies.
        /// </summary>
        public enum RetryStrategy
        {
            /// <summary>Exponential backoff strategy.</summary>
            BACKOFF,
            /// <summary>Exponential backoff strategy limited by retry attempt count.</summary>
            ATTEMPT_COUNT_BACKOFF,
            /// <summary>Disabled (no retries).</summary>
            NONE
        }

        /// <summary>The retry strategy.</summary>
        public readonly RetryStrategy Strategy;

        /// <summary>The backoff strategy configuration (if applicable).</summary>
        public readonly BackoffStrategy? Backoff;

        /// <summary>Whether to retry on connection errors.</summary>
        public readonly bool RetryConnectionErrors;

        /// <summary>Maximum retries after the initial request for attempt-count strategies.</summary>
        public readonly int? MaxRetries;

        /// <summary>
        /// Selects the retry strategy.
        /// </summary>
        /// <param name="strategy">The retry strategy.</param>
        /// <param name="backoff">The backoff strategy configuration (if applicable)</param>
        /// <param name="retryConnectionErrors">Whether to retry on connection errors.</param>
        /// <param name="maxRetries">Maximum retries after the initial request for attempt-count strategies.</param>
        /// <remarks>
        /// The backoff strategy is required if the retry strategy is set to BACKOFF or ATTEMPT_COUNT_BACKOFF.
        /// To disable retries, set the strategy to NONE.
        /// </remarks>
        public RetryConfig(
            RetryStrategy strategy,
            BackoffStrategy? backoff = null,
            bool retryConnectionErrors = false,
            int? maxRetries = null
        )
        {

            if ((strategy == RetryStrategy.BACKOFF || strategy == RetryStrategy.ATTEMPT_COUNT_BACKOFF) && backoff == null)
            {
                throw new System.ArgumentNullException("Backoff strategy configuration was not provided");
            }

            Strategy = strategy;
            Backoff = backoff;
            RetryConnectionErrors = retryConnectionErrors;
            MaxRetries = maxRetries;
        }
    }
}