//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Agents
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class AgentToolType
    {
        private AgentToolType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static AgentToolType CodeExecution
        {
            get {
                return new AgentToolType("code_execution");
            }
        }

        public static AgentToolType Function
        {
            get {
                return new AgentToolType("function");
            }
        }

        public static AgentToolType GoogleSearch
        {
            get {
                return new AgentToolType("google_search");
            }
        }

        public static AgentToolType McpServer
        {
            get {
                return new AgentToolType("mcp_server");
            }
        }

        public static AgentToolType UrlContext
        {
            get {
                return new AgentToolType("url_context");
            }
        }

        public static AgentToolType Unknown
        {
            get {
                return new AgentToolType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(AgentToolType v)
        {
            return v.Value;
        }
        public static AgentToolType FromString(string v)
        {
            switch (v)
            {
                case "code_execution":
                    return CodeExecution;
                case "function":
                    return Function;
                case "google_search":
                    return GoogleSearch;
                case "mcp_server":
                    return McpServer;
                case "url_context":
                    return UrlContext;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for AgentToolType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AgentToolType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// A tool that the agent can use.
    /// </summary>
    [JsonConverter(typeof(AgentTool.AgentToolConverter))]
    public class AgentTool : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public AgentTool(AgentToolType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public CodeExecution? CodeExecution { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Function? Function { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public GoogleSearch? GoogleSearch { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public MCPServer? MCPServer { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public URLContext? URLContext { get; set; }

        public AgentToolType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static AgentTool CreateUnknown(JToken raw)
        {
            return new AgentTool(AgentToolType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(AgentToolType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static AgentTool CreateCodeExecution(CodeExecution codeExecution)
        {
            AgentToolType typ = AgentToolType.CodeExecution;
            AgentTool res = new AgentTool(typ);
            res.CodeExecution = codeExecution;
            return res;
        }

        public static AgentTool CreateFunction(Function function)
        {
            AgentToolType typ = AgentToolType.Function;
            AgentTool res = new AgentTool(typ);
            res.Function = function;
            return res;
        }

        public static AgentTool CreateGoogleSearch(GoogleSearch googleSearch)
        {
            AgentToolType typ = AgentToolType.GoogleSearch;
            AgentTool res = new AgentTool(typ);
            res.GoogleSearch = googleSearch;
            return res;
        }

        public static AgentTool CreateMcpServer(MCPServer mcpServer)
        {
            AgentToolType typ = AgentToolType.McpServer;
            AgentTool res = new AgentTool(typ);
            res.MCPServer = mcpServer;
            return res;
        }

        public static AgentTool CreateUrlContext(URLContext urlContext)
        {
            AgentToolType typ = AgentToolType.UrlContext;
            AgentTool res = new AgentTool(typ);
            res.URLContext = urlContext;
            return res;
        }

        public class AgentToolConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(AgentTool);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken token = JToken.Load(reader);
                JObject? jo = token as JObject;
                if (jo == null)
                {
                    return CreateUnknown(token);
                }

                JToken? discriminatorToken = jo.GetValue("type");
                if (discriminatorToken == null || discriminatorToken.Type != JTokenType.String)
                {
                    return CreateUnknown(jo);
                }

                string discriminator = discriminatorToken.ToString();
                if (discriminator == AgentToolType.CodeExecution.ToString())
                {
                    CodeExecution codeExecution;
                    try
                    {
                        codeExecution = ResponseBodyDeserializer.DeserializeNotNull<CodeExecution>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<CodeExecution>(jo.ToString(), out codeExecution))
                        {
                            throw;
                        }
                    }
                    return CreateCodeExecution(codeExecution);
                }
                if (discriminator == AgentToolType.Function.ToString())
                {
                    Function function;
                    try
                    {
                        function = ResponseBodyDeserializer.DeserializeNotNull<Function>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<Function>(jo.ToString(), out function))
                        {
                            throw;
                        }
                    }
                    return CreateFunction(function);
                }
                if (discriminator == AgentToolType.GoogleSearch.ToString())
                {
                    GoogleSearch googleSearch;
                    try
                    {
                        googleSearch = ResponseBodyDeserializer.DeserializeNotNull<GoogleSearch>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<GoogleSearch>(jo.ToString(), out googleSearch))
                        {
                            throw;
                        }
                    }
                    return CreateGoogleSearch(googleSearch);
                }
                if (discriminator == AgentToolType.McpServer.ToString())
                {
                    MCPServer mcpServer;
                    try
                    {
                        mcpServer = ResponseBodyDeserializer.DeserializeNotNull<MCPServer>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<MCPServer>(jo.ToString(), out mcpServer))
                        {
                            throw;
                        }
                    }
                    return CreateMcpServer(mcpServer);
                }
                if (discriminator == AgentToolType.UrlContext.ToString())
                {
                    URLContext urlContext;
                    try
                    {
                        urlContext = ResponseBodyDeserializer.DeserializeNotNull<URLContext>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<URLContext>(jo.ToString(), out urlContext))
                        {
                            throw;
                        }
                    }
                    return CreateUrlContext(urlContext);
                }

                return CreateUnknown(jo);
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                AgentTool res = (AgentTool)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.CodeExecution != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CodeExecution));
                    return;
                }

                if (res.Function != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Function));
                    return;
                }

                if (res.GoogleSearch != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GoogleSearch));
                    return;
                }

                if (res.MCPServer != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MCPServer));
                    return;
                }

                if (res.URLContext != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.URLContext));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}