//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Agents
{
    using Google.GenAI.Gaos.Models.Agents;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class AgentListResponse
    {
        [JsonProperty("agents", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<Agent>? Agents { get; set; }

        [JsonProperty("next_page_token", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? NextPageToken { get; set; }
    }
}