// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Utils.Sse
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;

    /// <summary>
    /// Extension methods for HttpResponseMessage to enable Server-Sent Events streaming.
    /// </summary>
    public static class SseStreamExtensions
    {
        /// <summary>
        /// Converts an HttpResponseMessage to an EventStream for C# 5 compatible streaming.
        /// </summary>
        /// <typeparam name="T">The type to deserialize event data into.</typeparam>
        /// <param name="response">The HTTP response containing event stream data.</param>
        /// <param name="sentinelValue">Optional sentinel value that indicates end of stream.</param>
        /// <param name="dataRequired">Whether a data field is required for each event.</param>
        /// <returns>An EventStream for reading events one at a time.</returns>
        /// <exception cref="ArgumentNullException">Thrown when response is null.</exception>
        /// <exception cref="InvalidOperationException">Thrown when the response content type is not text/event-stream.</exception>
        public static async Task<EventStream<T>> AsServerSentEventStream<T>(
            this HttpResponseMessage response,
            string? sentinelValue = null,
            bool dataRequired = true)
        {
            // Validate content type
            if (!IsServerSentEventResponse(response))
            {
                var contentType = response.Content.Headers.ContentType?.MediaType;
                throw new InvalidOperationException(
                    $"Response content type '{contentType}' is not compatible with Server-Sent Events. Expected 'text/event-stream'.");
            }

            // Get the response stream
            var stream = await response.Content.ReadAsStreamAsync();

            // Create and return the event stream reader
            return new EventStream<T>(stream, sentinelValue, dataRequired);
        }

        /// <summary>
        /// Checks if the HttpResponseMessage contains Server-Sent Events content.
        /// </summary>
        /// <param name="response">The HTTP response to check.</param>
        /// <returns>True if the response contains SSE content, false otherwise.</returns>
        private static bool IsServerSentEventResponse(this HttpResponseMessage response)
        {
            if (response == null)
                return false;

            var contentType = response.Content.Headers.ContentType?.MediaType;
            return Utilities.IsContentTypeMatch("text/event-stream", contentType);
        }
    }
}