//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Code execution call step.
    /// </summary>
    public class CodeExecutionCallStep
    {
        /// <summary>
        /// The arguments to pass to the code execution.
        /// </summary>
        [JsonProperty("arguments", Required = Newtonsoft.Json.Required.Always)]
        public CodeExecutionCallArguments Arguments { get; set; } = new();

        /// <summary>
        /// Required. A unique ID for this specific tool call.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// A signature hash for backend validation.
        /// </summary>
        [JsonProperty("signature", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Signature { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "code_execution_call";
    }
}