//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ContentType
    {
        private ContentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ContentType Text
        {
            get {
                return new ContentType("text");
            }
        }

        public static ContentType Image
        {
            get {
                return new ContentType("image");
            }
        }

        public static ContentType Audio
        {
            get {
                return new ContentType("audio");
            }
        }

        public static ContentType Document
        {
            get {
                return new ContentType("document");
            }
        }

        public static ContentType Video
        {
            get {
                return new ContentType("video");
            }
        }

        public static ContentType Unknown
        {
            get {
                return new ContentType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ContentType v)
        {
            return v.Value;
        }
        public static ContentType FromString(string v)
        {
            switch (v)
            {
                case "text":
                    return Text;
                case "image":
                    return Image;
                case "audio":
                    return Audio;
                case "document":
                    return Document;
                case "video":
                    return Video;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for ContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The content of the response.
    /// </summary>
    [JsonConverter(typeof(Content.ContentConverter))]
    public class Content : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public Content(ContentType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public TextContent? TextContent { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public ImageContent? ImageContent { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public AudioContent? AudioContent { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public DocumentContent? DocumentContent { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public VideoContent? VideoContent { get; set; }

        public ContentType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static Content CreateUnknown(JToken raw)
        {
            return new Content(ContentType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(ContentType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static Content CreateText(TextContent text)
        {
            ContentType typ = ContentType.Text;
            Content res = new Content(typ);
            res.TextContent = text;
            return res;
        }

        public static Content CreateImage(ImageContent image)
        {
            ContentType typ = ContentType.Image;
            Content res = new Content(typ);
            res.ImageContent = image;
            return res;
        }

        public static Content CreateAudio(AudioContent audio)
        {
            ContentType typ = ContentType.Audio;
            Content res = new Content(typ);
            res.AudioContent = audio;
            return res;
        }

        public static Content CreateDocument(DocumentContent document)
        {
            ContentType typ = ContentType.Document;
            Content res = new Content(typ);
            res.DocumentContent = document;
            return res;
        }

        public static Content CreateVideo(VideoContent video)
        {
            ContentType typ = ContentType.Video;
            Content res = new Content(typ);
            res.VideoContent = video;
            return res;
        }

        public class ContentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Content);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken token = JToken.Load(reader);
                JObject? jo = token as JObject;
                if (jo == null)
                {
                    return CreateUnknown(token);
                }

                JToken? discriminatorToken = jo.GetValue("type");
                if (discriminatorToken == null || discriminatorToken.Type != JTokenType.String)
                {
                    return CreateUnknown(jo);
                }

                string discriminator = discriminatorToken.ToString();
                if (discriminator == ContentType.Text.ToString())
                {
                    TextContent textContent;
                    try
                    {
                        textContent = ResponseBodyDeserializer.DeserializeNotNull<TextContent>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<TextContent>(jo.ToString(), out textContent))
                        {
                            throw;
                        }
                    }
                    return CreateText(textContent);
                }
                if (discriminator == ContentType.Image.ToString())
                {
                    ImageContent imageContent;
                    try
                    {
                        imageContent = ResponseBodyDeserializer.DeserializeNotNull<ImageContent>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<ImageContent>(jo.ToString(), out imageContent))
                        {
                            throw;
                        }
                    }
                    return CreateImage(imageContent);
                }
                if (discriminator == ContentType.Audio.ToString())
                {
                    AudioContent audioContent;
                    try
                    {
                        audioContent = ResponseBodyDeserializer.DeserializeNotNull<AudioContent>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<AudioContent>(jo.ToString(), out audioContent))
                        {
                            throw;
                        }
                    }
                    return CreateAudio(audioContent);
                }
                if (discriminator == ContentType.Document.ToString())
                {
                    DocumentContent documentContent;
                    try
                    {
                        documentContent = ResponseBodyDeserializer.DeserializeNotNull<DocumentContent>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<DocumentContent>(jo.ToString(), out documentContent))
                        {
                            throw;
                        }
                    }
                    return CreateDocument(documentContent);
                }
                if (discriminator == ContentType.Video.ToString())
                {
                    VideoContent videoContent;
                    try
                    {
                        videoContent = ResponseBodyDeserializer.DeserializeNotNull<VideoContent>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<VideoContent>(jo.ToString(), out videoContent))
                        {
                            throw;
                        }
                    }
                    return CreateVideo(videoContent);
                }

                return CreateUnknown(jo);
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Content res = (Content)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.TextContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TextContent));
                    return;
                }

                if (res.ImageContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ImageContent));
                    return;
                }

                if (res.AudioContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AudioContent));
                    return;
                }

                if (res.DocumentContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DocumentContent));
                    return;
                }

                if (res.VideoContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.VideoContent));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}