// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CreateModelInteractionResponseFormatType
    {
        private CreateModelInteractionResponseFormatType(string value) { Value = value; }

        public string Value { get; private set; }

        public static CreateModelInteractionResponseFormatType ArrayOfResponseFormat { get { return new CreateModelInteractionResponseFormatType("arrayOfResponseFormat"); } }

        public static CreateModelInteractionResponseFormatType ResponseFormat { get { return new CreateModelInteractionResponseFormatType("ResponseFormat"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CreateModelInteractionResponseFormatType v) { return v.Value; }
        public static CreateModelInteractionResponseFormatType FromString(string v) {
            switch(v) {
                case "arrayOfResponseFormat": return ArrayOfResponseFormat;
                case "ResponseFormat": return ResponseFormat;
                default: throw new ArgumentException("Invalid value for CreateModelInteractionResponseFormatType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateModelInteractionResponseFormatType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
    /// </summary>
    [JsonConverter(typeof(CreateModelInteractionResponseFormat.CreateModelInteractionResponseFormatConverter))]
    public class CreateModelInteractionResponseFormat
    {
        public CreateModelInteractionResponseFormat(CreateModelInteractionResponseFormatType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public List<ResponseFormat>? ArrayOfResponseFormat { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseFormat? ResponseFormat { get; set; }

        public CreateModelInteractionResponseFormatType Type { get; set; }
        public static CreateModelInteractionResponseFormat CreateArrayOfResponseFormat(List<ResponseFormat> arrayOfResponseFormat)
        {
            CreateModelInteractionResponseFormatType typ = CreateModelInteractionResponseFormatType.ArrayOfResponseFormat;

            CreateModelInteractionResponseFormat res = new CreateModelInteractionResponseFormat(typ);
            res.ArrayOfResponseFormat = arrayOfResponseFormat;
            return res;
        }
        public static CreateModelInteractionResponseFormat CreateResponseFormat(ResponseFormat responseFormat)
        {
            CreateModelInteractionResponseFormatType typ = CreateModelInteractionResponseFormatType.ResponseFormat;

            CreateModelInteractionResponseFormat res = new CreateModelInteractionResponseFormat(typ);
            res.ResponseFormat = responseFormat;
            return res;
        }

        public class CreateModelInteractionResponseFormatConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateModelInteractionResponseFormat);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CreateModelInteractionResponseFormat(CreateModelInteractionResponseFormatType.ArrayOfResponseFormat)
                    {
                        ArrayOfResponseFormat = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<ResponseFormat>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<ResponseFormat>), new CreateModelInteractionResponseFormat(CreateModelInteractionResponseFormatType.ArrayOfResponseFormat), "ArrayOfResponseFormat"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CreateModelInteractionResponseFormat(CreateModelInteractionResponseFormatType.ResponseFormat)
                    {
                        ResponseFormat = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ResponseFormat>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ResponseFormat), new CreateModelInteractionResponseFormat(CreateModelInteractionResponseFormatType.ResponseFormat), "ResponseFormat"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CreateModelInteractionResponseFormat res = (CreateModelInteractionResponseFormat)value;

                if (res.ArrayOfResponseFormat != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfResponseFormat));
                    return;
                }

                if (res.ResponseFormat != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseFormat));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}