//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CreateAgentInteractionEnvironmentType
    {
        private CreateAgentInteractionEnvironmentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static CreateAgentInteractionEnvironmentType Str
        {
            get {
                return new CreateAgentInteractionEnvironmentType("str");
            }
        }

        public static CreateAgentInteractionEnvironmentType Environment
        {
            get {
                return new CreateAgentInteractionEnvironmentType("Environment");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(CreateAgentInteractionEnvironmentType v)
        {
            return v.Value;
        }
        public static CreateAgentInteractionEnvironmentType FromString(string v)
        {
            switch (v)
            {
                case "str":
                    return Str;
                case "Environment":
                    return Environment;
                default:
                    throw new ArgumentException("Invalid value for CreateAgentInteractionEnvironmentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateAgentInteractionEnvironmentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
    /// </summary>
    [JsonConverter(typeof(CreateAgentInteractionEnvironment.CreateAgentInteractionEnvironmentConverter))]
    public class CreateAgentInteractionEnvironment
    {
        public CreateAgentInteractionEnvironment(CreateAgentInteractionEnvironmentType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Models.Interactions.Environment? Environment { get; set; }

        public CreateAgentInteractionEnvironmentType Type { get; set; }
        public static CreateAgentInteractionEnvironment CreateStr(string str)
        {
            CreateAgentInteractionEnvironmentType typ = CreateAgentInteractionEnvironmentType.Str;

            CreateAgentInteractionEnvironment res = new CreateAgentInteractionEnvironment(typ);
            res.Str = str;
            return res;
        }
        public static CreateAgentInteractionEnvironment CreateEnvironment(Models.Interactions.Environment environment)
        {
            CreateAgentInteractionEnvironmentType typ = CreateAgentInteractionEnvironmentType.Environment;

            CreateAgentInteractionEnvironment res = new CreateAgentInteractionEnvironment(typ);
            res.Environment = environment;
            return res;
        }

        public class CreateAgentInteractionEnvironmentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateAgentInteractionEnvironment);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {

                    throw new JsonSerializationException("Received unexpected null JSON value");
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<CreateAgentInteractionEnvironmentType>();
                unionCandidates.Add<string>("Str", 0, CreateAgentInteractionEnvironmentType.Str);
                unionCandidates.Add<Models.Interactions.Environment>("Environment", 1, CreateAgentInteractionEnvironmentType.Environment);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    throw new ResponseBodyDeserializer.DeserializationException(typeof(CreateAgentInteractionEnvironment));
                }

                var result = new CreateAgentInteractionEnvironment(winner.TypeName);
                typeof(CreateAgentInteractionEnvironment).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CreateAgentInteractionEnvironment res = (CreateAgentInteractionEnvironment)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Environment != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Environment));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}