//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CreateModelInteractionEnvironmentType
    {
        private CreateModelInteractionEnvironmentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static CreateModelInteractionEnvironmentType Str
        {
            get {
                return new CreateModelInteractionEnvironmentType("str");
            }
        }

        public static CreateModelInteractionEnvironmentType Environment
        {
            get {
                return new CreateModelInteractionEnvironmentType("Environment");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(CreateModelInteractionEnvironmentType v)
        {
            return v.Value;
        }
        public static CreateModelInteractionEnvironmentType FromString(string v)
        {
            switch (v)
            {
                case "str":
                    return Str;
                case "Environment":
                    return Environment;
                default:
                    throw new ArgumentException("Invalid value for CreateModelInteractionEnvironmentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateModelInteractionEnvironmentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
    /// </summary>
    [JsonConverter(typeof(CreateModelInteractionEnvironment.CreateModelInteractionEnvironmentConverter))]
    public class CreateModelInteractionEnvironment
    {
        public CreateModelInteractionEnvironment(CreateModelInteractionEnvironmentType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Models.Interactions.Environment? Environment { get; set; }

        public CreateModelInteractionEnvironmentType Type { get; set; }
        public static CreateModelInteractionEnvironment CreateStr(string str)
        {
            CreateModelInteractionEnvironmentType typ = CreateModelInteractionEnvironmentType.Str;

            CreateModelInteractionEnvironment res = new CreateModelInteractionEnvironment(typ);
            res.Str = str;
            return res;
        }
        public static CreateModelInteractionEnvironment CreateEnvironment(Models.Interactions.Environment environment)
        {
            CreateModelInteractionEnvironmentType typ = CreateModelInteractionEnvironmentType.Environment;

            CreateModelInteractionEnvironment res = new CreateModelInteractionEnvironment(typ);
            res.Environment = environment;
            return res;
        }

        public class CreateModelInteractionEnvironmentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateModelInteractionEnvironment);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {

                    throw new JsonSerializationException("Received unexpected null JSON value");
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<CreateModelInteractionEnvironmentType>();
                unionCandidates.Add<string>("Str", 0, CreateModelInteractionEnvironmentType.Str);
                unionCandidates.Add<Models.Interactions.Environment>("Environment", 1, CreateModelInteractionEnvironmentType.Environment);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    throw new ResponseBodyDeserializer.DeserializationException(typeof(CreateModelInteractionEnvironment));
                }

                var result = new CreateModelInteractionEnvironment(winner.TypeName);
                typeof(CreateModelInteractionEnvironment).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CreateModelInteractionEnvironment res = (CreateModelInteractionEnvironment)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Environment != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Environment));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}