// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Configuration for the Deep Research agent.
    /// </summary>
    public class DeepResearchAgentConfig
    {
        /// <summary>
        /// Enables human-in-the-loop planning for the Deep Research agent. If set to<br/>
        /// true, the Deep Research agent will provide a research plan in its response.<br/>
        /// The agent will then proceed only if the user confirms the plan in the next<br/>
        /// turn.
        /// </summary>
        [JsonProperty("collaborative_planning")]
        public bool? CollaborativePlanning { get; set; }

        /// <summary>
        /// Enables bigquery tool for the Deep Research agent.
        /// </summary>
        [JsonProperty("enable_bigquery_tool")]
        public bool? EnableBigqueryTool { get; set; }

        [JsonProperty("thinking_summaries")]
        public ThinkingSummaries? ThinkingSummaries { get; set; }

        [JsonProperty("type")]
        public string Type { get; } = "deep-research";

        /// <summary>
        /// Whether to include visualizations in the response.
        /// </summary>
        [JsonProperty("visualization")]
        public Visualization? Visualization { get; set; }
    }
}