//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class DisabledSafetyPolicy : IEquatable<DisabledSafetyPolicy>, IOpenEnum<string>
    {
        public static readonly DisabledSafetyPolicy FinancialTransactions = new DisabledSafetyPolicy("financial_transactions");
        public static readonly DisabledSafetyPolicy SensitiveDataModification = new DisabledSafetyPolicy("sensitive_data_modification");
        public static readonly DisabledSafetyPolicy CommunicationTool = new DisabledSafetyPolicy("communication_tool");
        public static readonly DisabledSafetyPolicy AccountCreation = new DisabledSafetyPolicy("account_creation");
        public static readonly DisabledSafetyPolicy DataModification = new DisabledSafetyPolicy("data_modification");
        public static readonly DisabledSafetyPolicy UserConsentManagement = new DisabledSafetyPolicy("user_consent_management");
        public static readonly DisabledSafetyPolicy LegalTermsAndAgreements = new DisabledSafetyPolicy("legal_terms_and_agreements");

        private static readonly Dictionary<string, DisabledSafetyPolicy> _knownValues =
            new Dictionary<string, DisabledSafetyPolicy>() {
                ["financial_transactions"] = FinancialTransactions,
                ["sensitive_data_modification"] = SensitiveDataModification,
                ["communication_tool"] = CommunicationTool,
                ["account_creation"] = AccountCreation,
                ["data_modification"] = DataModification,
                ["user_consent_management"] = UserConsentManagement,
                ["legal_terms_and_agreements"] = LegalTermsAndAgreements
            };

        private static readonly ConcurrentDictionary<string, DisabledSafetyPolicy> _values =
            new ConcurrentDictionary<string, DisabledSafetyPolicy>(_knownValues);

        private DisabledSafetyPolicy(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static DisabledSafetyPolicy Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new DisabledSafetyPolicy(value));
        }

        public static implicit operator DisabledSafetyPolicy(string value) => Of(value);
        public static implicit operator string(DisabledSafetyPolicy disabledsafetypolicy) => disabledsafetypolicy.Value;

        public static DisabledSafetyPolicy[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as DisabledSafetyPolicy);

        public bool Equals(DisabledSafetyPolicy? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}