//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The mime type of the document.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class DocumentContentMimeType : IEquatable<DocumentContentMimeType>, IOpenEnum<string>
    {
        public static readonly DocumentContentMimeType ApplicationPdf = new DocumentContentMimeType("application/pdf");
        public static readonly DocumentContentMimeType TextCsv = new DocumentContentMimeType("text/csv");

        private static readonly Dictionary<string, DocumentContentMimeType> _knownValues =
            new Dictionary<string, DocumentContentMimeType>() {
                ["application/pdf"] = ApplicationPdf,
                ["text/csv"] = TextCsv
            };

        private static readonly ConcurrentDictionary<string, DocumentContentMimeType> _values =
            new ConcurrentDictionary<string, DocumentContentMimeType>(_knownValues);

        private DocumentContentMimeType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static DocumentContentMimeType Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new DocumentContentMimeType(value));
        }

        public static implicit operator DocumentContentMimeType(string value) => Of(value);
        public static implicit operator string(DocumentContentMimeType documentcontentmimetype) => documentcontentmimetype.Value;

        public static DocumentContentMimeType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as DocumentContentMimeType);

        public bool Equals(DocumentContentMimeType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}