// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class EnvironmentNetworkEgressAllowlistType
    {
        private EnvironmentNetworkEgressAllowlistType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static EnvironmentNetworkEgressAllowlistType Allowlist
        {
            get {
                return new EnvironmentNetworkEgressAllowlistType("Allowlist");
            }
        }

        public static EnvironmentNetworkEgressAllowlistType Disabled
        {
            get {
                return new EnvironmentNetworkEgressAllowlistType("Disabled");
            }
        }

        public static EnvironmentNetworkEgressAllowlistType Unknown
        {
            get {
                return new EnvironmentNetworkEgressAllowlistType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(EnvironmentNetworkEgressAllowlistType v)
        {
            return v.Value;
        }
        public static EnvironmentNetworkEgressAllowlistType FromString(string v)
        {
            switch (v)
            {
                case "Allowlist":
                    return Allowlist;
                case "Disabled":
                    return Disabled;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for EnvironmentNetworkEgressAllowlistType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((EnvironmentNetworkEgressAllowlistType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Outbound networking configuration for the sandbox. Accepts an object with an 'allowlist' array to restrict traffic, or the string 'disabled' to turn off all network access. Omit entirely to allow all outbound traffic with no header injection.
    /// </summary>
    [JsonConverter(typeof(EnvironmentNetworkEgressAllowlist.EnvironmentNetworkEgressAllowlistConverter))]
    public class EnvironmentNetworkEgressAllowlist : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public EnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlistType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Allowlist? Allowlist { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Disabled? Disabled { get; set; }

        public EnvironmentNetworkEgressAllowlistType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static EnvironmentNetworkEgressAllowlist CreateUnknown(JToken raw)
        {
            return new EnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlistType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(EnvironmentNetworkEgressAllowlistType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static EnvironmentNetworkEgressAllowlist CreateAllowlist(Allowlist allowlist)
        {
            EnvironmentNetworkEgressAllowlistType typ = EnvironmentNetworkEgressAllowlistType.Allowlist;

            EnvironmentNetworkEgressAllowlist res = new EnvironmentNetworkEgressAllowlist(typ);
            res.Allowlist = allowlist;
            return res;
        }
        public static EnvironmentNetworkEgressAllowlist CreateDisabled(Disabled disabled)
        {
            EnvironmentNetworkEgressAllowlistType typ = EnvironmentNetworkEgressAllowlistType.Disabled;

            EnvironmentNetworkEgressAllowlist res = new EnvironmentNetworkEgressAllowlist(typ);
            res.Disabled = disabled;
            return res;
        }

        public class EnvironmentNetworkEgressAllowlistConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(EnvironmentNetworkEgressAllowlist);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }
                var json = Utilities.LoadRawToken(reader).ToString(Newtonsoft.Json.Formatting.None);
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new EnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlistType.Allowlist) {
                        Allowlist = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Allowlist>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Allowlist), new EnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlistType.Allowlist), "Allowlist"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new EnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlistType.Disabled) {
                        Disabled = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Disabled>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Disabled), new EnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlistType.Disabled), "Disabled"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                return CreateUnknown(Utilities.ParseRawToken(json));
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                EnvironmentNetworkEgressAllowlist res = (EnvironmentNetworkEgressAllowlist)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.Allowlist != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Allowlist));
                    return;
                }

                if (res.Disabled != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Disabled));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}