//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// A file citation annotation.
    /// </summary>
    public class FileCitation
    {
        /// <summary>
        /// User provided metadata about the retrieved context.
        /// </summary>
        [JsonProperty("custom_metadata", Required = Newtonsoft.Json.Required.DisallowNull)]
        public Dictionary<string, object>? CustomMetadata { get; set; }

        /// <summary>
        /// The URI of the file.
        /// </summary>
        [JsonProperty("document_uri", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? DocumentUri { get; set; }

        /// <summary>
        /// End of the attributed segment, exclusive.
        /// </summary>
        [JsonProperty("end_index", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? EndIndex { get; set; }

        /// <summary>
        /// The name of the file.
        /// </summary>
        [JsonProperty("file_name", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? FileName { get; set; }

        /// <summary>
        /// Media ID in-case of image citations, if applicable.
        /// </summary>
        [JsonProperty("media_id", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? MediaId { get; set; }

        /// <summary>
        /// Page number of the cited document, if applicable.
        /// </summary>
        [JsonProperty("page_number", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? PageNumber { get; set; }

        /// <summary>
        /// Source attributed for a portion of the text.
        /// </summary>
        [JsonProperty("source", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Source { get; set; }

        /// <summary>
        /// Start of segment of the response that is attributed to this source.<br/>
        /// <br/>
        /// Index indicates the start of the segment, measured in bytes.
        /// </summary>
        [JsonProperty("start_index", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? StartIndex { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "file_citation";
    }
}