//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Content of a single file in the codebase.
    /// </summary>
    public class FileContent
    {
        /// <summary>
        /// The UTF-8 encoded text content of the file.
        /// </summary>
        [JsonProperty("content", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Content { get; set; }

        /// <summary>
        /// The relative path of the file from the project root.
        /// </summary>
        [JsonProperty("path", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Path { get; set; }
    }
}