//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Config for filters.
    /// </summary>
    public class Filter
    {
        /// <summary>
        /// Optional. String for metadata filtering.
        /// </summary>
        [JsonProperty("metadata_filter", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? MetadataFilter { get; set; }

        /// <summary>
        /// Optional. Only returns contexts with vector distance smaller than the<br/>
        /// threshold.
        /// </summary>
        [JsonProperty("vector_distance_threshold", Required = Newtonsoft.Json.Required.DisallowNull)]
        public double? VectorDistanceThreshold { get; set; }

        /// <summary>
        /// Optional. Only returns contexts with vector similarity larger than the<br/>
        /// threshold.
        /// </summary>
        [JsonProperty("vector_similarity_threshold", Required = Newtonsoft.Json.Required.DisallowNull)]
        public double? VectorSimilarityThreshold { get; set; }
    }
}