// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Request parameters specific to FIND sessions, used for discovering<br/>
    /// vulnerabilities in a codebase.
    /// </summary>
    public class FindRequest
    {
        /// <summary>
        /// Additional context or custom instructions provided by the user to guide<br/>
        /// the vulnerability analysis.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The identifier of a specific finding to verify. This is primarily used in<br/>
        /// VERIFY mode to focus the agent's execution-based validation on a single<br/>
        /// vulnerability.
        /// </summary>
        [JsonProperty("finding_id")]
        public string? FindingId { get; set; }

        /// <summary>
        /// The mode of the find session.
        /// </summary>
        [JsonProperty("mode")]
        public Mode? Mode { get; set; }

        /// <summary>
        /// A list of source files to provide as context for the scan.
        /// </summary>
        [JsonProperty("source_files")]
        public List<FileContent>? SourceFiles { get; set; }
    }
}