//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// A tool that can be used by the model.
    /// </summary>
    public class Function
    {
        /// <summary>
        /// A description of the function.
        /// </summary>
        [JsonProperty("description", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Description { get; set; }

        /// <summary>
        /// The name of the function.
        /// </summary>
        [JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Name { get; set; }

        /// <summary>
        /// The JSON Schema for the function's parameters.
        /// </summary>
        [JsonProperty("parameters", Required = Newtonsoft.Json.Required.DisallowNull)]
        public object? Parameters { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "function";
    }
}