//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// A function tool call step.
    /// </summary>
    public class FunctionCallStep
    {
        /// <summary>
        /// Required. The arguments to pass to the function.
        /// </summary>
        [JsonProperty("arguments", Required = Newtonsoft.Json.Required.Always)]
        public Dictionary<string, object> Arguments { get; set; } = default!;

        /// <summary>
        /// Required. A unique ID for this specific tool call.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Required. The name of the tool to call.
        /// </summary>
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "function_call";
    }
}