// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Configuration parameters for model interactions.
    /// </summary>
    public class GenerationConfig
    {
        /// <summary>
        /// The configuration for image interaction.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("image_config")]
        public ImageConfig? ImageConfig { get; set; }

        /// <summary>
        /// The maximum number of tokens to include in the response.
        /// </summary>
        [JsonProperty("max_output_tokens")]
        public int? MaxOutputTokens { get; set; }

        /// <summary>
        /// Seed used in decoding for reproducibility.
        /// </summary>
        [JsonProperty("seed")]
        public int? Seed { get; set; }

        /// <summary>
        /// Configuration for speech interaction.
        /// </summary>
        [JsonProperty("speech_config")]
        public List<SpeechConfig>? SpeechConfig { get; set; }

        /// <summary>
        /// A list of character sequences that will stop output interaction.
        /// </summary>
        [JsonProperty("stop_sequences")]
        public List<string>? StopSequences { get; set; }

        /// <summary>
        /// Controls the randomness of the output.
        /// </summary>
        [JsonProperty("temperature")]
        public float? Temperature { get; set; }

        [JsonProperty("thinking_level")]
        public ThinkingLevel? ThinkingLevel { get; set; }

        [JsonProperty("thinking_summaries")]
        public ThinkingSummaries? ThinkingSummaries { get; set; }

        /// <summary>
        /// The tool choice configuration.
        /// </summary>
        [JsonProperty("tool_choice", NullValueHandling = NullValueHandling.Include)]
        public ToolChoice? ToolChoice { get; set; }

        /// <summary>
        /// The maximum cumulative probability of tokens to consider when sampling.
        /// </summary>
        [JsonProperty("top_p")]
        public float? TopP { get; set; }

        /// <summary>
        /// Configuration options for video generation.
        /// </summary>
        [JsonProperty("video_config")]
        public VideoConfig? VideoConfig { get; set; }
    }
}