//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Configuration parameters for model interactions.
    /// </summary>
    public class GenerationConfig
    {
        /// <summary>
        /// The configuration for image interaction.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("image_config", Required = Newtonsoft.Json.Required.DisallowNull)]
        public ImageConfig? ImageConfig { get; set; }

        /// <summary>
        /// The maximum number of tokens to include in the response.
        /// </summary>
        [JsonProperty("max_output_tokens", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? MaxOutputTokens { get; set; }

        /// <summary>
        /// Seed used in decoding for reproducibility.
        /// </summary>
        [JsonProperty("seed", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? Seed { get; set; }

        /// <summary>
        /// A list of character sequences that will stop output interaction.
        /// </summary>
        [JsonProperty("stop_sequences", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<string>? StopSequences { get; set; }

        [JsonProperty("thinking_level", Required = Newtonsoft.Json.Required.DisallowNull)]
        public ThinkingLevel? ThinkingLevel { get; set; }

        [JsonProperty("thinking_summaries", Required = Newtonsoft.Json.Required.DisallowNull)]
        public ThinkingSummaries? ThinkingSummaries { get; set; }

        /// <summary>
        /// The tool choice configuration.
        /// </summary>
        [JsonProperty("tool_choice", Required = Newtonsoft.Json.Required.DisallowNull)]
        public ToolChoice? ToolChoice { get; set; }

        /// <summary>
        /// Configuration for speech recognition (transcription).
        /// </summary>
        [JsonProperty("transcription_config", Required = Newtonsoft.Json.Required.DisallowNull)]
        public TranscriptionConfig? TranscriptionConfig { get; set; }

        /// <summary>
        /// Configuration options for video generation.
        /// </summary>
        [JsonProperty("video_config", Required = Newtonsoft.Json.Required.DisallowNull)]
        public VideoConfig? VideoConfig { get; set; }

        /// <summary>
        /// Optional. Speech and multi-speaker configuration.
        /// </summary>
        [JsonProperty("speech_config", Required = Newtonsoft.Json.Required.DisallowNull)]
        public SpeechConfigUnion? SpeechConfig { get; set; }
    }
}