//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    public class GoogleMapsCallDelta
    {
        /// <summary>
        /// The arguments to pass to the Google Maps tool.
        /// </summary>
        [JsonProperty("arguments", Required = Newtonsoft.Json.Required.DisallowNull)]
        public GoogleMapsCallArguments? Arguments { get; set; }

        /// <summary>
        /// A signature hash for backend validation.
        /// </summary>
        [JsonProperty("signature", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Signature { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "google_maps_call";
    }
}