//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class GoogleSearchSearchType : IEquatable<GoogleSearchSearchType>, IOpenEnum<string>
    {
        public static readonly GoogleSearchSearchType WebSearch = new GoogleSearchSearchType("web_search");
        public static readonly GoogleSearchSearchType ImageSearch = new GoogleSearchSearchType("image_search");
        public static readonly GoogleSearchSearchType EnterpriseWebSearch = new GoogleSearchSearchType("enterprise_web_search");

        private static readonly Dictionary<string, GoogleSearchSearchType> _knownValues =
            new Dictionary<string, GoogleSearchSearchType>() {
                ["web_search"] = WebSearch,
                ["image_search"] = ImageSearch,
                ["enterprise_web_search"] = EnterpriseWebSearch
            };

        private static readonly ConcurrentDictionary<string, GoogleSearchSearchType> _values =
            new ConcurrentDictionary<string, GoogleSearchSearchType>(_knownValues);

        private GoogleSearchSearchType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GoogleSearchSearchType Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new GoogleSearchSearchType(value));
        }

        public static implicit operator GoogleSearchSearchType(string value) => Of(value);
        public static implicit operator string(GoogleSearchSearchType googlesearchsearchtype) => googlesearchsearchtype.Value;

        public static GoogleSearchSearchType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GoogleSearchSearchType);

        public bool Equals(GoogleSearchSearchType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}