//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class GoogleSearchResultDelta
    {
        [JsonProperty("is_error", Required = Newtonsoft.Json.Required.DisallowNull)]
        public bool? IsError { get; set; }

        [JsonProperty("result", Required = Newtonsoft.Json.Required.Always)]
        public List<GoogleSearchResult> Result { get; set; } = default!;

        /// <summary>
        /// A signature hash for backend validation.
        /// </summary>
        [JsonProperty("signature", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Signature { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "google_search_result";
    }
}