//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// The result of the Google Maps.
    /// </summary>
    public class GoogleMapsResult
    {
        [JsonProperty("places", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<GoogleMapsResultPlaces>? Places { get; set; }

        [JsonProperty("widget_context_token", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? WidgetContextToken { get; set; }
    }
}