//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A tool that can be used by the model to search Google.
    /// </summary>
    public class GoogleSearch
    {
        /// <summary>
        /// The types of search grounding to enable.
        /// </summary>
        [JsonProperty("search_types", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<GoogleSearchSearchType>? SearchTypes { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "google_search";
    }
}