// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Google Maps result step.
    /// </summary>
    public class GoogleMapsResultStep
    {
        [JsonProperty("type")]
        public string Type { get; } = "google_maps_result";

        [JsonProperty("result")]
        public List<GoogleMapsResult> Result { get; set; } = default!;

        /// <summary>
        /// Required. ID to match the ID from the function call block.
        /// </summary>
        [JsonProperty("call_id")]
        public string CallId { get; set; } = default!;

        /// <summary>
        /// A signature hash for backend validation.
        /// </summary>
        [JsonProperty("signature")]
        public string? Signature { get; set; }
    }
}