//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Google Search call step.
    /// </summary>
    public class GoogleSearchCallStep
    {
        /// <summary>
        /// The arguments to pass to Google Search.
        /// </summary>
        [JsonProperty("arguments", Required = Newtonsoft.Json.Required.Always)]
        public GoogleSearchCallArguments Arguments { get; set; } = new();

        /// <summary>
        /// Required. A unique ID for this specific tool call.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The type of search grounding enabled.
        /// </summary>
        [JsonProperty("search_type", Required = Newtonsoft.Json.Required.DisallowNull)]
        public GoogleSearchCallStepSearchType? SearchType { get; set; }

        /// <summary>
        /// A signature hash for backend validation.
        /// </summary>
        [JsonProperty("signature", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Signature { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "google_search_call";
    }
}