// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The grounding tool type associated with the count.
    /// </summary>
    public enum GroundingToolCountType
    {
        [JsonProperty("google_search")] GoogleSearch,
        [JsonProperty("google_maps")] GoogleMaps,
        [JsonProperty("retrieval")] Retrieval,
    }

    public static class GroundingToolCountTypeExtension
    {
        public static string Value(this GroundingToolCountType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GroundingToolCountType ToEnum(this string value)
        {
            foreach (var field in typeof(GroundingToolCountType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GroundingToolCountType)
                    {
                        return (GroundingToolCountType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GroundingToolCountType");
        }
    }
}