//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class HarmCategory : IEquatable<HarmCategory>, IOpenEnum<string>
    {
        public static readonly HarmCategory HateSpeech = new HarmCategory("hate_speech");
        public static readonly HarmCategory DangerousContent = new HarmCategory("dangerous_content");
        public static readonly HarmCategory Harassment = new HarmCategory("harassment");
        public static readonly HarmCategory SexuallyExplicit = new HarmCategory("sexually_explicit");
        public static readonly HarmCategory CivicIntegrity = new HarmCategory("civic_integrity");
        public static readonly HarmCategory ImageHate = new HarmCategory("image_hate");
        public static readonly HarmCategory ImageDangerousContent = new HarmCategory("image_dangerous_content");
        public static readonly HarmCategory ImageHarassment = new HarmCategory("image_harassment");
        public static readonly HarmCategory ImageSexuallyExplicit = new HarmCategory("image_sexually_explicit");
        public static readonly HarmCategory Jailbreak = new HarmCategory("jailbreak");

        private static readonly Dictionary<string, HarmCategory> _knownValues =
            new Dictionary<string, HarmCategory>() {
                ["hate_speech"] = HateSpeech,
                ["dangerous_content"] = DangerousContent,
                ["harassment"] = Harassment,
                ["sexually_explicit"] = SexuallyExplicit,
                ["civic_integrity"] = CivicIntegrity,
                ["image_hate"] = ImageHate,
                ["image_dangerous_content"] = ImageDangerousContent,
                ["image_harassment"] = ImageHarassment,
                ["image_sexually_explicit"] = ImageSexuallyExplicit,
                ["jailbreak"] = Jailbreak
            };

        private static readonly ConcurrentDictionary<string, HarmCategory> _values =
            new ConcurrentDictionary<string, HarmCategory>(_knownValues);

        private HarmCategory(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static HarmCategory Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new HarmCategory(value));
        }

        public static implicit operator HarmCategory(string value) => Of(value);
        public static implicit operator string(HarmCategory harmcategory) => harmcategory.Value;

        public static HarmCategory[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as HarmCategory);

        public bool Equals(HarmCategory? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}