//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Config for Hybrid Search.
    /// </summary>
    public class HybridSearch
    {
        /// <summary>
        /// Optional. Alpha value controls the weight between dense and sparse vector search<br/>
        /// results.
        /// </summary>
        [JsonProperty("alpha", Required = Newtonsoft.Json.Required.DisallowNull)]
        public float? Alpha { get; set; }
    }
}