//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ImageConfigAspectRatio : IEquatable<ImageConfigAspectRatio>, IOpenEnum<string>
    {
        public static readonly ImageConfigAspectRatio Eleven = new ImageConfigAspectRatio("1:1");
        public static readonly ImageConfigAspectRatio TwentyThree = new ImageConfigAspectRatio("2:3");
        public static readonly ImageConfigAspectRatio ThirtyTwo = new ImageConfigAspectRatio("3:2");
        public static readonly ImageConfigAspectRatio ThirtyFour = new ImageConfigAspectRatio("3:4");
        public static readonly ImageConfigAspectRatio FortyThree = new ImageConfigAspectRatio("4:3");
        public static readonly ImageConfigAspectRatio FortyFive = new ImageConfigAspectRatio("4:5");
        public static readonly ImageConfigAspectRatio FiftyFour = new ImageConfigAspectRatio("5:4");
        public static readonly ImageConfigAspectRatio NineHundredAndSixteen = new ImageConfigAspectRatio("9:16");
        public static readonly ImageConfigAspectRatio OneHundredAndSixtyNine = new ImageConfigAspectRatio("16:9");
        public static readonly ImageConfigAspectRatio TwoHundredAndNineteen = new ImageConfigAspectRatio("21:9");
        public static readonly ImageConfigAspectRatio Eighteen = new ImageConfigAspectRatio("1:8");
        public static readonly ImageConfigAspectRatio EightyOne = new ImageConfigAspectRatio("8:1");
        public static readonly ImageConfigAspectRatio Fourteen = new ImageConfigAspectRatio("1:4");
        public static readonly ImageConfigAspectRatio FortyOne = new ImageConfigAspectRatio("4:1");

        private static readonly Dictionary<string, ImageConfigAspectRatio> _knownValues =
            new Dictionary<string, ImageConfigAspectRatio>() {
                ["1:1"] = Eleven,
                ["2:3"] = TwentyThree,
                ["3:2"] = ThirtyTwo,
                ["3:4"] = ThirtyFour,
                ["4:3"] = FortyThree,
                ["4:5"] = FortyFive,
                ["5:4"] = FiftyFour,
                ["9:16"] = NineHundredAndSixteen,
                ["16:9"] = OneHundredAndSixtyNine,
                ["21:9"] = TwoHundredAndNineteen,
                ["1:8"] = Eighteen,
                ["8:1"] = EightyOne,
                ["1:4"] = Fourteen,
                ["4:1"] = FortyOne
            };

        private static readonly ConcurrentDictionary<string, ImageConfigAspectRatio> _values =
            new ConcurrentDictionary<string, ImageConfigAspectRatio>(_knownValues);

        private ImageConfigAspectRatio(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ImageConfigAspectRatio Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ImageConfigAspectRatio(value));
        }

        public static implicit operator ImageConfigAspectRatio(string value) => Of(value);
        public static implicit operator string(ImageConfigAspectRatio imageconfigaspectratio) => imageconfigaspectratio.Value;

        public static ImageConfigAspectRatio[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ImageConfigAspectRatio);

        public bool Equals(ImageConfigAspectRatio? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}