//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The size of the image output.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ImageResponseFormatImageSize : IEquatable<ImageResponseFormatImageSize>, IOpenEnum<string>
    {
        public static readonly ImageResponseFormatImageSize FiveHundredAndTwelve = new ImageResponseFormatImageSize("512");
        public static readonly ImageResponseFormatImageSize OneK = new ImageResponseFormatImageSize("1K");
        public static readonly ImageResponseFormatImageSize TwoK = new ImageResponseFormatImageSize("2K");
        public static readonly ImageResponseFormatImageSize FourK = new ImageResponseFormatImageSize("4K");

        private static readonly Dictionary<string, ImageResponseFormatImageSize> _knownValues =
            new Dictionary<string, ImageResponseFormatImageSize>() {
                ["512"] = FiveHundredAndTwelve,
                ["1K"] = OneK,
                ["2K"] = TwoK,
                ["4K"] = FourK
            };

        private static readonly ConcurrentDictionary<string, ImageResponseFormatImageSize> _values =
            new ConcurrentDictionary<string, ImageResponseFormatImageSize>(_knownValues);

        private ImageResponseFormatImageSize(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ImageResponseFormatImageSize Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ImageResponseFormatImageSize(value));
        }

        public static implicit operator ImageResponseFormatImageSize(string value) => Of(value);
        public static implicit operator string(ImageResponseFormatImageSize imageresponseformatimagesize) => imageresponseformatimagesize.Value;

        public static ImageResponseFormatImageSize[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ImageResponseFormatImageSize);

        public bool Equals(ImageResponseFormatImageSize? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}