// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Configuration for image output format.
    /// </summary>
    public class ImageResponseFormat
    {
        /// <summary>
        /// The aspect ratio for the image output.
        /// </summary>
        [JsonProperty("aspect_ratio")]
        public ImageResponseFormatAspectRatio? AspectRatio { get; set; }

        /// <summary>
        /// The delivery mode for the image output.
        /// </summary>
        [JsonProperty("delivery")]
        public ImageResponseFormatDelivery? Delivery { get; set; }

        /// <summary>
        /// The size of the image output.
        /// </summary>
        [JsonProperty("image_size")]
        public ImageResponseFormatImageSize? ImageSize { get; set; }

        /// <summary>
        /// The MIME type of the image output.
        /// </summary>
        [JsonProperty("mime_type")]
        public ImageResponseFormatMimeType? MimeType { get; set; }

        [JsonProperty("type")]
        public string Type { get; } = "image";
    }
}