//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class InteractionEnvironmentType
    {
        private InteractionEnvironmentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static InteractionEnvironmentType Str
        {
            get {
                return new InteractionEnvironmentType("str");
            }
        }

        public static InteractionEnvironmentType Environment
        {
            get {
                return new InteractionEnvironmentType("Environment");
            }
        }

        public static InteractionEnvironmentType Unknown
        {
            get {
                return new InteractionEnvironmentType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(InteractionEnvironmentType v)
        {
            return v.Value;
        }
        public static InteractionEnvironmentType FromString(string v)
        {
            switch (v)
            {
                case "str":
                    return Str;
                case "Environment":
                    return Environment;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for InteractionEnvironmentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((InteractionEnvironmentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
    /// </summary>
    [JsonConverter(typeof(InteractionEnvironment.InteractionEnvironmentConverter))]
    public class InteractionEnvironment : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public InteractionEnvironment(InteractionEnvironmentType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Models.Interactions.Environment? Environment { get; set; }

        public InteractionEnvironmentType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static InteractionEnvironment CreateUnknown(JToken raw)
        {
            return new InteractionEnvironment(InteractionEnvironmentType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(InteractionEnvironmentType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static InteractionEnvironment CreateStr(string str)
        {
            InteractionEnvironmentType typ = InteractionEnvironmentType.Str;

            InteractionEnvironment res = new InteractionEnvironment(typ);
            res.Str = str;
            return res;
        }
        public static InteractionEnvironment CreateEnvironment(Models.Interactions.Environment environment)
        {
            InteractionEnvironmentType typ = InteractionEnvironmentType.Environment;

            InteractionEnvironment res = new InteractionEnvironment(typ);
            res.Environment = environment;
            return res;
        }

        public class InteractionEnvironmentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(InteractionEnvironment);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<InteractionEnvironmentType>();
                unionCandidates.Add<string>("Str", 0, InteractionEnvironmentType.Str);
                unionCandidates.Add<Models.Interactions.Environment>("Environment", 1, InteractionEnvironmentType.Environment);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    return CreateUnknown(jt);
                }

                var result = new InteractionEnvironment(winner.TypeName);
                typeof(InteractionEnvironment).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                InteractionEnvironment res = (InteractionEnvironment)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Environment != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Environment));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}