//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Required. Output only. The status of the interaction.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class InteractionSseEventInteractionStatus : IEquatable<InteractionSseEventInteractionStatus>, IOpenEnum<string>
    {
        public static readonly InteractionSseEventInteractionStatus InProgress = new InteractionSseEventInteractionStatus("in_progress");
        public static readonly InteractionSseEventInteractionStatus RequiresAction = new InteractionSseEventInteractionStatus("requires_action");
        public static readonly InteractionSseEventInteractionStatus Completed = new InteractionSseEventInteractionStatus("completed");
        public static readonly InteractionSseEventInteractionStatus Failed = new InteractionSseEventInteractionStatus("failed");
        public static readonly InteractionSseEventInteractionStatus Cancelled = new InteractionSseEventInteractionStatus("cancelled");
        public static readonly InteractionSseEventInteractionStatus Incomplete = new InteractionSseEventInteractionStatus("incomplete");

        private static readonly Dictionary<string, InteractionSseEventInteractionStatus> _knownValues =
            new Dictionary<string, InteractionSseEventInteractionStatus>() {
                ["in_progress"] = InProgress,
                ["requires_action"] = RequiresAction,
                ["completed"] = Completed,
                ["failed"] = Failed,
                ["cancelled"] = Cancelled,
                ["incomplete"] = Incomplete
            };

        private static readonly ConcurrentDictionary<string, InteractionSseEventInteractionStatus> _values =
            new ConcurrentDictionary<string, InteractionSseEventInteractionStatus>(_knownValues);

        private InteractionSseEventInteractionStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static InteractionSseEventInteractionStatus Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new InteractionSseEventInteractionStatus(value));
        }

        public static implicit operator InteractionSseEventInteractionStatus(string value) => Of(value);
        public static implicit operator string(InteractionSseEventInteractionStatus interactionsseeventinteractionstatus) => interactionsseeventinteractionstatus.Value;

        public static InteractionSseEventInteractionStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as InteractionSseEventInteractionStatus);

        public bool Equals(InteractionSseEventInteractionStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}