//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    public class InteractionCompletedEvent
    {
        [JsonProperty("event_type", Required = Newtonsoft.Json.Required.Always)]
        public string EventType { get; } = "interaction.completed";

        /// <summary>
        /// The event_id token to be used to resume the interaction stream, from<br/>
        /// this event.
        /// </summary>
        [JsonProperty("event_id", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? EventId { get; set; }

        /// <summary>
        /// Partial interaction resource emitted by interaction lifecycle SSE events.<br/>
        /// Streaming lifecycle payloads may omit fields that are only available on<br/>
        /// full non-streaming Interaction responses.
        /// </summary>
        [JsonProperty("interaction", Required = Newtonsoft.Json.Required.Always)]
        public InteractionSseEventInteraction Interaction { get; set; } = new();
    }
}