//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class MCPServerToolResultStepResultUnionType
    {
        private MCPServerToolResultStepResultUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static MCPServerToolResultStepResultUnionType MCPServerToolResultStepResult
        {
            get {
                return new MCPServerToolResultStepResultUnionType("MCPServerToolResultStep_result");
            }
        }

        public static MCPServerToolResultStepResultUnionType Str
        {
            get {
                return new MCPServerToolResultStepResultUnionType("str");
            }
        }

        public static MCPServerToolResultStepResultUnionType ArrayOfFunctionResultSubcontent
        {
            get {
                return new MCPServerToolResultStepResultUnionType("arrayOfFunctionResultSubcontent");
            }
        }

        public static MCPServerToolResultStepResultUnionType Unknown
        {
            get {
                return new MCPServerToolResultStepResultUnionType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(MCPServerToolResultStepResultUnionType v)
        {
            return v.Value;
        }
        public static MCPServerToolResultStepResultUnionType FromString(string v)
        {
            switch (v)
            {
                case "MCPServerToolResultStep_result":
                    return MCPServerToolResultStepResult;
                case "str":
                    return Str;
                case "arrayOfFunctionResultSubcontent":
                    return ArrayOfFunctionResultSubcontent;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for MCPServerToolResultStepResultUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MCPServerToolResultStepResultUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The output from the MCP server call. Can be simple text or rich content.
    /// </summary>
    [JsonConverter(typeof(MCPServerToolResultStepResultUnion.MCPServerToolResultStepResultUnionConverter))]
    public class MCPServerToolResultStepResultUnion : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public MCPServerToolResultStepResult? MCPServerToolResultStepResult { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public List<FunctionResultSubcontent>? ArrayOfFunctionResultSubcontent { get; set; }

        public MCPServerToolResultStepResultUnionType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static MCPServerToolResultStepResultUnion CreateUnknown(JToken raw)
        {
            return new MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(MCPServerToolResultStepResultUnionType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static MCPServerToolResultStepResultUnion CreateMCPServerToolResultStepResult(MCPServerToolResultStepResult mcpServerToolResultStepResult)
        {
            MCPServerToolResultStepResultUnionType typ = MCPServerToolResultStepResultUnionType.MCPServerToolResultStepResult;

            MCPServerToolResultStepResultUnion res = new MCPServerToolResultStepResultUnion(typ);
            res.MCPServerToolResultStepResult = mcpServerToolResultStepResult;
            return res;
        }
        public static MCPServerToolResultStepResultUnion CreateStr(string str)
        {
            MCPServerToolResultStepResultUnionType typ = MCPServerToolResultStepResultUnionType.Str;

            MCPServerToolResultStepResultUnion res = new MCPServerToolResultStepResultUnion(typ);
            res.Str = str;
            return res;
        }
        public static MCPServerToolResultStepResultUnion CreateArrayOfFunctionResultSubcontent(List<FunctionResultSubcontent> arrayOfFunctionResultSubcontent)
        {
            MCPServerToolResultStepResultUnionType typ = MCPServerToolResultStepResultUnionType.ArrayOfFunctionResultSubcontent;

            MCPServerToolResultStepResultUnion res = new MCPServerToolResultStepResultUnion(typ);
            res.ArrayOfFunctionResultSubcontent = arrayOfFunctionResultSubcontent;
            return res;
        }

        public class MCPServerToolResultStepResultUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(MCPServerToolResultStepResultUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<MCPServerToolResultStepResultUnionType>();
                unionCandidates.Add<MCPServerToolResultStepResult>("MCPServerToolResultStepResult", 0, MCPServerToolResultStepResultUnionType.MCPServerToolResultStepResult);
                unionCandidates.Add<string>("Str", 1, MCPServerToolResultStepResultUnionType.Str);
                unionCandidates.Add<List<FunctionResultSubcontent>>("ArrayOfFunctionResultSubcontent", 2, MCPServerToolResultStepResultUnionType.ArrayOfFunctionResultSubcontent);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    return CreateUnknown(jt);
                }

                var result = new MCPServerToolResultStepResultUnion(winner.TypeName);
                typeof(MCPServerToolResultStepResultUnion).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                MCPServerToolResultStepResultUnion res = (MCPServerToolResultStepResultUnion)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.MCPServerToolResultStepResult != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MCPServerToolResultStepResult));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.ArrayOfFunctionResultSubcontent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfFunctionResultSubcontent));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}