// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class MCPServerToolResultStepResultUnionType
    {
        private MCPServerToolResultStepResultUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static MCPServerToolResultStepResultUnionType MCPServerToolResultStepResult { get { return new MCPServerToolResultStepResultUnionType("MCPServerToolResultStep_result"); } }

        public static MCPServerToolResultStepResultUnionType Str { get { return new MCPServerToolResultStepResultUnionType("str"); } }

        public static MCPServerToolResultStepResultUnionType ArrayOfFunctionResultSubcontent { get { return new MCPServerToolResultStepResultUnionType("arrayOfFunctionResultSubcontent"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(MCPServerToolResultStepResultUnionType v) { return v.Value; }
        public static MCPServerToolResultStepResultUnionType FromString(string v) {
            switch(v) {
                case "MCPServerToolResultStep_result": return MCPServerToolResultStepResult;
                case "str": return Str;
                case "arrayOfFunctionResultSubcontent": return ArrayOfFunctionResultSubcontent;
                default: throw new ArgumentException("Invalid value for MCPServerToolResultStepResultUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MCPServerToolResultStepResultUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The output from the MCP server call. Can be simple text or rich content.
    /// </summary>
    [JsonConverter(typeof(MCPServerToolResultStepResultUnion.MCPServerToolResultStepResultUnionConverter))]
    public class MCPServerToolResultStepResultUnion
    {
        public MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public MCPServerToolResultStepResult? MCPServerToolResultStepResult { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<FunctionResultSubcontent>? ArrayOfFunctionResultSubcontent { get; set; }

        public MCPServerToolResultStepResultUnionType Type { get; set; }
        public static MCPServerToolResultStepResultUnion CreateMCPServerToolResultStepResult(MCPServerToolResultStepResult mcpServerToolResultStepResult)
        {
            MCPServerToolResultStepResultUnionType typ = MCPServerToolResultStepResultUnionType.MCPServerToolResultStepResult;

            MCPServerToolResultStepResultUnion res = new MCPServerToolResultStepResultUnion(typ);
            res.MCPServerToolResultStepResult = mcpServerToolResultStepResult;
            return res;
        }
        public static MCPServerToolResultStepResultUnion CreateStr(string str)
        {
            MCPServerToolResultStepResultUnionType typ = MCPServerToolResultStepResultUnionType.Str;

            MCPServerToolResultStepResultUnion res = new MCPServerToolResultStepResultUnion(typ);
            res.Str = str;
            return res;
        }
        public static MCPServerToolResultStepResultUnion CreateArrayOfFunctionResultSubcontent(List<FunctionResultSubcontent> arrayOfFunctionResultSubcontent)
        {
            MCPServerToolResultStepResultUnionType typ = MCPServerToolResultStepResultUnionType.ArrayOfFunctionResultSubcontent;

            MCPServerToolResultStepResultUnion res = new MCPServerToolResultStepResultUnion(typ);
            res.ArrayOfFunctionResultSubcontent = arrayOfFunctionResultSubcontent;
            return res;
        }

        public class MCPServerToolResultStepResultUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(MCPServerToolResultStepResultUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType.MCPServerToolResultStepResult)
                    {
                        MCPServerToolResultStepResult = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<MCPServerToolResultStepResult>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(MCPServerToolResultStepResult), new MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType.MCPServerToolResultStepResult), "MCPServerToolResultStepResult"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType.ArrayOfFunctionResultSubcontent)
                    {
                        ArrayOfFunctionResultSubcontent = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<FunctionResultSubcontent>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<FunctionResultSubcontent>), new MCPServerToolResultStepResultUnion(MCPServerToolResultStepResultUnionType.ArrayOfFunctionResultSubcontent), "ArrayOfFunctionResultSubcontent"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                MCPServerToolResultStepResultUnion res = (MCPServerToolResultStepResultUnion)value;

                if (res.MCPServerToolResultStepResult != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MCPServerToolResultStepResult));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.ArrayOfFunctionResultSubcontent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfFunctionResultSubcontent));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}