//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class MediaResolution : IEquatable<MediaResolution>, IOpenEnum<string>
    {
        public static readonly MediaResolution Low = new MediaResolution("low");
        public static readonly MediaResolution Medium = new MediaResolution("medium");
        public static readonly MediaResolution High = new MediaResolution("high");
        public static readonly MediaResolution UltraHigh = new MediaResolution("ultra_high");

        private static readonly Dictionary<string, MediaResolution> _knownValues =
            new Dictionary<string, MediaResolution>() {
                ["low"] = Low,
                ["medium"] = Medium,
                ["high"] = High,
                ["ultra_high"] = UltraHigh
            };

        private static readonly ConcurrentDictionary<string, MediaResolution> _values =
            new ConcurrentDictionary<string, MediaResolution>(_knownValues);

        private MediaResolution(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static MediaResolution Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new MediaResolution(value));
        }

        public static implicit operator MediaResolution(string value) => Of(value);
        public static implicit operator string(MediaResolution mediaresolution) => mediaresolution.Value;

        public static MediaResolution[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as MediaResolution);

        public bool Equals(MediaResolution? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}