// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Output generated by the model.
    /// </summary>
    public class ModelOutputStep
    {
        [JsonProperty("content")]
        public List<Content>? Content { get; set; }

        /// <summary>
        /// The `Status` type defines a logical error model that is suitable for<br/>
        /// different programming environments, including REST APIs and RPC APIs. It is<br/>
        /// used by <a href="https://github.com/grpc">gRPC</a>. Each `Status` message contains<br/>
        /// three pieces of data: error code, error message, and error details.<br/>
        /// <br/>
        /// You can find out more about this error model and how to work with it in the<br/>
        /// <a href="https://cloud.google.com/apis/design/errors">API Design Guide</a>.
        /// </summary>
        [JsonProperty("error")]
        public Status? Error { get; set; }

        [JsonProperty("type")]
        public string Type { get; } = "model_output";
    }
}