// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class NetworkType
    {
        private NetworkType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static NetworkType EnvironmentNetworkEgressAllowlist
        {
            get {
                return new NetworkType("EnvironmentNetworkEgressAllowlist");
            }
        }

        public static NetworkType NetworkEnum
        {
            get {
                return new NetworkType("network_enum");
            }
        }

        public static NetworkType Unknown
        {
            get {
                return new NetworkType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(NetworkType v)
        {
            return v.Value;
        }
        public static NetworkType FromString(string v)
        {
            switch (v)
            {
                case "EnvironmentNetworkEgressAllowlist":
                    return EnvironmentNetworkEgressAllowlist;
                case "network_enum":
                    return NetworkEnum;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for NetworkType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((NetworkType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Network configuration for the environment.
    /// </summary>
    [JsonConverter(typeof(Network.NetworkConverter))]
    public class Network : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public Network(NetworkType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public EnvironmentNetworkEgressAllowlist? EnvironmentNetworkEgressAllowlist { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public NetworkEnum? NetworkEnum { get; set; }

        public NetworkType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static Network CreateUnknown(JToken raw)
        {
            return new Network(NetworkType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(NetworkType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static Network CreateEnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlist environmentNetworkEgressAllowlist)
        {
            NetworkType typ = NetworkType.EnvironmentNetworkEgressAllowlist;

            Network res = new Network(typ);
            res.EnvironmentNetworkEgressAllowlist = environmentNetworkEgressAllowlist;
            return res;
        }
        public static Network CreateNetworkEnum(NetworkEnum networkEnum)
        {
            NetworkType typ = NetworkType.NetworkEnum;

            Network res = new Network(typ);
            res.NetworkEnum = networkEnum;
            return res;
        }

        public class NetworkConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Network);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }
                var json = Utilities.LoadRawToken(reader).ToString(Newtonsoft.Json.Formatting.None);
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Network(NetworkType.EnvironmentNetworkEgressAllowlist) {
                        EnvironmentNetworkEgressAllowlist = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<EnvironmentNetworkEgressAllowlist>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(EnvironmentNetworkEgressAllowlist), new Network(NetworkType.EnvironmentNetworkEgressAllowlist), "EnvironmentNetworkEgressAllowlist"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Network(NetworkType.NetworkEnum) {
                        NetworkEnum = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<NetworkEnum>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(NetworkEnum), new Network(NetworkType.NetworkEnum), "NetworkEnum"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                return CreateUnknown(Utilities.ParseRawToken(json));
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Network res = (Network)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.EnvironmentNetworkEgressAllowlist != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.EnvironmentNetworkEgressAllowlist));
                    return;
                }

                if (res.NetworkEnum != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.NetworkEnum));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}