//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// A place citation annotation.
    /// </summary>
    public class PlaceCitation
    {
        /// <summary>
        /// End of the attributed segment, exclusive.
        /// </summary>
        [JsonProperty("end_index", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? EndIndex { get; set; }

        /// <summary>
        /// Title of the place.
        /// </summary>
        [JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Name { get; set; }

        /// <summary>
        /// The ID of the place, in `places/{place_id}` format.
        /// </summary>
        [JsonProperty("place_id", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? PlaceId { get; set; }

        /// <summary>
        /// Snippets of reviews that are used to generate answers about the<br/>
        /// features of a given place in Google Maps.
        /// </summary>
        [JsonProperty("review_snippets", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<ReviewSnippet>? ReviewSnippets { get; set; }

        /// <summary>
        /// Start of segment of the response that is attributed to this source.<br/>
        /// <br/>
        /// Index indicates the start of the segment, measured in bytes.
        /// </summary>
        [JsonProperty("start_index", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? StartIndex { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "place_citation";

        /// <summary>
        /// URI reference of the place.
        /// </summary>
        [JsonProperty("url", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Url { get; set; }
    }
}