// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// A place citation annotation.
    /// </summary>
    public class PlaceCitation
    {
        [JsonProperty("type")]
        public string Type { get; } = "place_citation";

        /// <summary>
        /// The ID of the place, in `places/{place_id}` format.
        /// </summary>
        [JsonProperty("place_id")]
        public string? PlaceId { get; set; }

        /// <summary>
        /// Title of the place.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// URI reference of the place.
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }

        /// <summary>
        /// Snippets of reviews that are used to generate answers about the<br/>
        /// features of a given place in Google Maps.
        /// </summary>
        [JsonProperty("review_snippets")]
        public List<ReviewSnippet>? ReviewSnippets { get; set; }

        /// <summary>
        /// Start of segment of the response that is attributed to this source.<br/>
        /// <br/>
        /// Index indicates the start of the segment, measured in bytes.
        /// </summary>
        [JsonProperty("start_index")]
        public int? StartIndex { get; set; }

        /// <summary>
        /// End of the attributed segment, exclusive.
        /// </summary>
        [JsonProperty("end_index")]
        public int? EndIndex { get; set; }
    }
}