//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using System.Numerics;
    using System.Reflection;

    public class ProcessingType
    {
        private ProcessingType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ProcessingType MediaProcessing
        {
            get {
                return new ProcessingType("MediaProcessing");
            }
        }

        public static ProcessingType ProcessingEnum
        {
            get {
                return new ProcessingType("processing_enum");
            }
        }

        public static ProcessingType Unknown
        {
            get {
                return new ProcessingType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ProcessingType v)
        {
            return v.Value;
        }
        public static ProcessingType FromString(string v)
        {
            switch (v)
            {
                case "MediaProcessing":
                    return MediaProcessing;
                case "processing_enum":
                    return ProcessingEnum;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for ProcessingType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ProcessingType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// How the model processes this video for understanding.
    /// </summary>
    [JsonConverter(typeof(Processing.ProcessingConverter))]
    public class Processing : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public Processing(ProcessingType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public MediaProcessing? MediaProcessing { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public ProcessingEnum? ProcessingEnum { get; set; }

        public ProcessingType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static Processing CreateUnknown(JToken raw)
        {
            return new Processing(ProcessingType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(ProcessingType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static Processing CreateMediaProcessing(MediaProcessing mediaProcessing)
        {
            ProcessingType typ = ProcessingType.MediaProcessing;

            Processing res = new Processing(typ);
            res.MediaProcessing = mediaProcessing;
            return res;
        }
        public static Processing CreateProcessingEnum(ProcessingEnum processingEnum)
        {
            ProcessingType typ = ProcessingType.ProcessingEnum;

            Processing res = new Processing(typ);
            res.ProcessingEnum = processingEnum;
            return res;
        }

        public class ProcessingConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Processing);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<ProcessingType>();
                unionCandidates.Add<MediaProcessing>("MediaProcessing", 0, ProcessingType.MediaProcessing);
                unionCandidates.Add<ProcessingEnum>("ProcessingEnum", 1, ProcessingType.ProcessingEnum);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    return CreateUnknown(jt);
                }

                var result = new Processing(winner.TypeName);
                typeof(Processing).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Processing res = (Processing)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.MediaProcessing != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MediaProcessing));
                    return;
                }

                if (res.ProcessingEnum != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ProcessingEnum));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}