// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Use to specify configuration for RAG Store.
    /// </summary>
    public class RagStoreConfig
    {
        /// <summary>
        /// Optional. The representation of the rag source.
        /// </summary>
        [JsonProperty("rag_resources")]
        public List<RagResource>? RagResources { get; set; }

        /// <summary>
        /// Specifies the context retrieval config.
        /// </summary>
        [JsonProperty("rag_retrieval_config")]
        public RagRetrievalConfig? RagRetrievalConfig { get; set; }

        /// <summary>
        /// Optional. Number of top k results to return from the selected corpora.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("similarity_top_k")]
        public int? SimilarityTopK { get; set; }

        /// <summary>
        /// Optional. Only return results with vector distance smaller than the threshold.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("vector_distance_threshold")]
        public double? VectorDistanceThreshold { get; set; }
    }
}