//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ResponseFormatType
    {
        private ResponseFormatType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ResponseFormatType AudioResponseFormat
        {
            get {
                return new ResponseFormatType("AudioResponseFormat");
            }
        }

        public static ResponseFormatType ImageResponseFormat
        {
            get {
                return new ResponseFormatType("ImageResponseFormat");
            }
        }

        public static ResponseFormatType TextResponseFormat
        {
            get {
                return new ResponseFormatType("TextResponseFormat");
            }
        }

        public static ResponseFormatType VideoResponseFormat
        {
            get {
                return new ResponseFormatType("VideoResponseFormat");
            }
        }

        public static ResponseFormatType MapOfAny
        {
            get {
                return new ResponseFormatType("mapOfAny");
            }
        }

        public static ResponseFormatType Unknown
        {
            get {
                return new ResponseFormatType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ResponseFormatType v)
        {
            return v.Value;
        }
        public static ResponseFormatType FromString(string v)
        {
            switch (v)
            {
                case "AudioResponseFormat":
                    return AudioResponseFormat;
                case "ImageResponseFormat":
                    return ImageResponseFormat;
                case "TextResponseFormat":
                    return TextResponseFormat;
                case "VideoResponseFormat":
                    return VideoResponseFormat;
                case "mapOfAny":
                    return MapOfAny;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for ResponseFormatType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponseFormatType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(ResponseFormat.ResponseFormatConverter))]
    public class ResponseFormat : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public ResponseFormat(ResponseFormatType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public AudioResponseFormat? AudioResponseFormat { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public ImageResponseFormat? ImageResponseFormat { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public TextResponseFormat? TextResponseFormat { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public VideoResponseFormat? VideoResponseFormat { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        public ResponseFormatType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static ResponseFormat CreateUnknown(JToken raw)
        {
            return new ResponseFormat(ResponseFormatType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(ResponseFormatType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static ResponseFormat CreateAudioResponseFormat(AudioResponseFormat audioResponseFormat)
        {
            ResponseFormatType typ = ResponseFormatType.AudioResponseFormat;

            ResponseFormat res = new ResponseFormat(typ);
            res.AudioResponseFormat = audioResponseFormat;
            return res;
        }
        public static ResponseFormat CreateImageResponseFormat(ImageResponseFormat imageResponseFormat)
        {
            ResponseFormatType typ = ResponseFormatType.ImageResponseFormat;

            ResponseFormat res = new ResponseFormat(typ);
            res.ImageResponseFormat = imageResponseFormat;
            return res;
        }
        public static ResponseFormat CreateTextResponseFormat(TextResponseFormat textResponseFormat)
        {
            ResponseFormatType typ = ResponseFormatType.TextResponseFormat;

            ResponseFormat res = new ResponseFormat(typ);
            res.TextResponseFormat = textResponseFormat;
            return res;
        }
        public static ResponseFormat CreateVideoResponseFormat(VideoResponseFormat videoResponseFormat)
        {
            ResponseFormatType typ = ResponseFormatType.VideoResponseFormat;

            ResponseFormat res = new ResponseFormat(typ);
            res.VideoResponseFormat = videoResponseFormat;
            return res;
        }
        public static ResponseFormat CreateMapOfAny(Dictionary<string, object> mapOfAny)
        {
            ResponseFormatType typ = ResponseFormatType.MapOfAny;

            ResponseFormat res = new ResponseFormat(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }

        public class ResponseFormatConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponseFormat);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<ResponseFormatType>();
                unionCandidates.Add<AudioResponseFormat>("AudioResponseFormat", 0, ResponseFormatType.AudioResponseFormat);
                unionCandidates.Add<ImageResponseFormat>("ImageResponseFormat", 1, ResponseFormatType.ImageResponseFormat);
                unionCandidates.Add<TextResponseFormat>("TextResponseFormat", 2, ResponseFormatType.TextResponseFormat);
                unionCandidates.Add<VideoResponseFormat>("VideoResponseFormat", 3, ResponseFormatType.VideoResponseFormat);
                unionCandidates.Add<Dictionary<string, object>>("MapOfAny", 4, ResponseFormatType.MapOfAny);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    return CreateUnknown(jt);
                }

                var result = new ResponseFormat(winner.TypeName);
                typeof(ResponseFormat).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ResponseFormat res = (ResponseFormat)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.AudioResponseFormat != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AudioResponseFormat));
                    return;
                }

                if (res.ImageResponseFormat != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ImageResponseFormat));
                    return;
                }

                if (res.TextResponseFormat != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TextResponseFormat));
                    return;
                }

                if (res.VideoResponseFormat != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.VideoResponseFormat));
                    return;
                }

                if (res.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfAny));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}