//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The type of retrieval tools.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class RetrievalCallDeltaRetrievalType : IEquatable<RetrievalCallDeltaRetrievalType>, IOpenEnum<string>
    {
        public static readonly RetrievalCallDeltaRetrievalType VertexAiSearch = new RetrievalCallDeltaRetrievalType("vertex_ai_search");
        public static readonly RetrievalCallDeltaRetrievalType RagStore = new RetrievalCallDeltaRetrievalType("rag_store");
        public static readonly RetrievalCallDeltaRetrievalType ExaAiSearch = new RetrievalCallDeltaRetrievalType("exa_ai_search");
        public static readonly RetrievalCallDeltaRetrievalType ParallelAiSearch = new RetrievalCallDeltaRetrievalType("parallel_ai_search");

        private static readonly Dictionary<string, RetrievalCallDeltaRetrievalType> _knownValues =
            new Dictionary<string, RetrievalCallDeltaRetrievalType>() {
                ["vertex_ai_search"] = VertexAiSearch,
                ["rag_store"] = RagStore,
                ["exa_ai_search"] = ExaAiSearch,
                ["parallel_ai_search"] = ParallelAiSearch
            };

        private static readonly ConcurrentDictionary<string, RetrievalCallDeltaRetrievalType> _values =
            new ConcurrentDictionary<string, RetrievalCallDeltaRetrievalType>(_knownValues);

        private RetrievalCallDeltaRetrievalType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static RetrievalCallDeltaRetrievalType Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new RetrievalCallDeltaRetrievalType(value));
        }

        public static implicit operator RetrievalCallDeltaRetrievalType(string value) => Of(value);
        public static implicit operator string(RetrievalCallDeltaRetrievalType retrievalcalldeltaretrievaltype) => retrievalcalldeltaretrievaltype.Value;

        public static RetrievalCallDeltaRetrievalType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as RetrievalCallDeltaRetrievalType);

        public bool Equals(RetrievalCallDeltaRetrievalType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}