//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Used by Vertex Retrieval tools such as Parallel AI, Exa AI, Vertex AI Search,<br/>
    /// etc.<br/>
    /// ToolResultDelta.type.
    /// </summary>
    public class RetrievalResultDelta
    {
        /// <summary>
        /// Whether the retrieval resulted in an error.
        /// </summary>
        [JsonProperty("is_error", Required = Newtonsoft.Json.Required.DisallowNull)]
        public bool? IsError { get; set; }

        /// <summary>
        /// A signature hash for backend validation.
        /// </summary>
        [JsonProperty("signature", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Signature { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "retrieval_result";
    }
}