//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A safety setting that affects the safety-blocking behavior.<br/>
    /// <br/>
    /// A SafetySetting consists of a<br/>
    /// harm category and a<br/>
    /// threshold for that<br/>
    /// category.
    /// </summary>
    public class SafetySetting
    {
        /// <summary>
        /// Optional. The method for blocking content. If not specified, the default<br/>
        /// behavior is to use the probability score.
        /// </summary>
        [JsonProperty("method", Required = Newtonsoft.Json.Required.DisallowNull)]
        public Method? Method { get; set; }

        /// <summary>
        /// Required. The threshold for blocking content. If the harm probability<br/>
        /// exceeds this threshold, the content will be blocked.
        /// </summary>
        [JsonProperty("threshold", Required = Newtonsoft.Json.Required.Always)]
        public Threshold Threshold { get; set; } = default!;

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public HarmCategory Type { get; set; } = default!;
    }
}