// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// A source to be mounted into the environment.
    /// </summary>
    public class Source
    {
        /// <summary>
        /// The inline content if `type` is `INLINE`.
        /// </summary>
        [JsonProperty("content")]
        public string? Content { get; set; }

        /// <summary>
        /// Optional encoding for inline content (e.g. `base64`).
        /// </summary>
        [JsonProperty("encoding")]
        public string? Encoding { get; set; }

        /// <summary>
        /// The source of the environment.<br/>
        /// For GCS, this is the GCS path.<br/>
        /// For GitHub, this is the GitHub path.
        /// </summary>
        [JsonProperty("source")]
        public string? SourceValue { get; set; }

        /// <summary>
        /// Where the source should appear in the environment.
        /// </summary>
        [JsonProperty("target")]
        public string? Target { get; set; }

        [JsonProperty("type")]
        public SourceType? Type { get; set; }
    }
}