//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A source to be mounted into the environment.
    /// </summary>
    public class Source
    {
        /// <summary>
        /// The inline content if `type` is `INLINE`.
        /// </summary>
        [JsonProperty("content", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Content { get; set; }

        /// <summary>
        /// Optional encoding for inline content (e.g. `base64`).
        /// </summary>
        [JsonProperty("encoding", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Encoding { get; set; }

        /// <summary>
        /// The source of the environment.<br/>
        /// For GCS, this is the GCS path.<br/>
        /// For GitHub, this is the GitHub path.
        /// </summary>
        [JsonProperty("source", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? SourceValue { get; set; }

        /// <summary>
        /// Where the source should appear in the environment.
        /// </summary>
        [JsonProperty("target", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Target { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull)]
        public SourceType? Type { get; set; }
    }
}