//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Configuration for multi-speaker and speech generation.
    /// </summary>
    public class SpeakerConfig
    {
        /// <summary>
        /// Individual speaker configurations.
        /// </summary>
        [JsonProperty("speakers", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<SpeechConfig>? Speakers { get; set; }
    }
}