//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// The configuration for speech interaction.
    /// </summary>
    public class SpeechConfig
    {
        /// <summary>
        /// The language of the speech.
        /// </summary>
        [JsonProperty("language", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Language { get; set; }

        /// <summary>
        /// The speaker's name, it should match the speaker name given in the prompt.
        /// </summary>
        [JsonProperty("speaker", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Speaker { get; set; }

        /// <summary>
        /// The voice of the speaker.
        /// </summary>
        [JsonProperty("voice", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Voice { get; set; }
    }
}