// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class SpeechConfigUnionType
    {
        private SpeechConfigUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static SpeechConfigUnionType SpeakerConfig
        {
            get {
                return new SpeechConfigUnionType("SpeakerConfig");
            }
        }

        public static SpeechConfigUnionType ArrayOfSpeechConfig
        {
            get {
                return new SpeechConfigUnionType("arrayOfSpeechConfig");
            }
        }

        public static SpeechConfigUnionType Unknown
        {
            get {
                return new SpeechConfigUnionType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(SpeechConfigUnionType v)
        {
            return v.Value;
        }
        public static SpeechConfigUnionType FromString(string v)
        {
            switch (v)
            {
                case "SpeakerConfig":
                    return SpeakerConfig;
                case "arrayOfSpeechConfig":
                    return ArrayOfSpeechConfig;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for SpeechConfigUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SpeechConfigUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Optional. Speech and multi-speaker configuration.
    /// </summary>
    [JsonConverter(typeof(SpeechConfigUnion.SpeechConfigUnionConverter))]
    public class SpeechConfigUnion : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public SpeechConfigUnion(SpeechConfigUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public SpeakerConfig? SpeakerConfig { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<SpeechConfig>? ArrayOfSpeechConfig { get; set; }

        public SpeechConfigUnionType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static SpeechConfigUnion CreateUnknown(JToken raw)
        {
            return new SpeechConfigUnion(SpeechConfigUnionType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(SpeechConfigUnionType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static SpeechConfigUnion CreateSpeakerConfig(SpeakerConfig speakerConfig)
        {
            SpeechConfigUnionType typ = SpeechConfigUnionType.SpeakerConfig;

            SpeechConfigUnion res = new SpeechConfigUnion(typ);
            res.SpeakerConfig = speakerConfig;
            return res;
        }
        public static SpeechConfigUnion CreateArrayOfSpeechConfig(List<SpeechConfig> arrayOfSpeechConfig)
        {
            SpeechConfigUnionType typ = SpeechConfigUnionType.ArrayOfSpeechConfig;

            SpeechConfigUnion res = new SpeechConfigUnion(typ);
            res.ArrayOfSpeechConfig = arrayOfSpeechConfig;
            return res;
        }

        public class SpeechConfigUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(SpeechConfigUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }
                var json = Utilities.LoadRawToken(reader).ToString(Newtonsoft.Json.Formatting.None);
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new SpeechConfigUnion(SpeechConfigUnionType.SpeakerConfig) {
                        SpeakerConfig = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SpeakerConfig>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SpeakerConfig), new SpeechConfigUnion(SpeechConfigUnionType.SpeakerConfig), "SpeakerConfig"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new SpeechConfigUnion(SpeechConfigUnionType.ArrayOfSpeechConfig) {
                        ArrayOfSpeechConfig = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<SpeechConfig>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<SpeechConfig>), new SpeechConfigUnion(SpeechConfigUnionType.ArrayOfSpeechConfig), "ArrayOfSpeechConfig"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                return CreateUnknown(Utilities.ParseRawToken(json));
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                SpeechConfigUnion res = (SpeechConfigUnion)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.SpeakerConfig != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SpeakerConfig));
                    return;
                }

                if (res.ArrayOfSpeechConfig != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfSpeechConfig));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}