// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    public class StaticMediaProcessing
    {
        /// <summary>
        /// Optional. Segment end time. Specified as a decimal number of seconds followed<br/>
        /// by an 's' suffix, e.g., "30s". Must be non-negative and greater than<br/>
        /// `start_offset` if `start_offset` is set.
        /// </summary>
        [JsonProperty("end_offset")]
        public string? EndOffset { get; set; }

        /// <summary>
        /// Optional. Video frame-rate sampling density.
        /// </summary>
        [JsonProperty("fps")]
        public double? Fps { get; set; }

        /// <summary>
        /// Optional. Segment start time. Specified as a decimal number of seconds followed<br/>
        /// by an 's' suffix, e.g., "10.5s". Must be non-negative.
        /// </summary>
        [JsonProperty("start_offset")]
        public string? StartOffset { get; set; }

        [JsonProperty("type")]
        public string Type { get; } = "static";
    }
}