// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    public class StepDelta
    {
        [JsonProperty("event_type")]
        public string EventType { get; } = "step.delta";

        [JsonProperty("index")]
        public int Index { get; set; } = default!;

        [JsonProperty("delta", NullValueHandling = NullValueHandling.Include)]
        public StepDeltaData Delta { get; set; } = default!;

        public TextDelta? GetDeltaText()
        {
            return Delta.TextDelta;
        }

        public ImageDelta? GetDeltaImage()
        {
            return Delta.ImageDelta;
        }

        public AudioDelta? GetDeltaAudio()
        {
            return Delta.AudioDelta;
        }

        public DocumentDelta? GetDeltaDocument()
        {
            return Delta.DocumentDelta;
        }

        public VideoDelta? GetDeltaVideo()
        {
            return Delta.VideoDelta;
        }

        public ThoughtSummaryDelta? GetDeltaThoughtSummary()
        {
            return Delta.ThoughtSummaryDelta;
        }

        public ThoughtSignatureDelta? GetDeltaThoughtSignature()
        {
            return Delta.ThoughtSignatureDelta;
        }

        public TextAnnotationDelta? GetDeltaTextAnnotationDelta()
        {
            return Delta.TextAnnotationDelta;
        }

        public ArgumentsDelta? GetDeltaArgumentsDelta()
        {
            return Delta.ArgumentsDelta;
        }

        public CodeExecutionCallDelta? GetDeltaCodeExecutionCall()
        {
            return Delta.CodeExecutionCallDelta;
        }

        public URLContextCallDelta? GetDeltaUrlContextCall()
        {
            return Delta.URLContextCallDelta;
        }

        public GoogleSearchCallDelta? GetDeltaGoogleSearchCall()
        {
            return Delta.GoogleSearchCallDelta;
        }

        public MCPServerToolCallDelta? GetDeltaMcpServerToolCall()
        {
            return Delta.MCPServerToolCallDelta;
        }

        public FileSearchCallDelta? GetDeltaFileSearchCall()
        {
            return Delta.FileSearchCallDelta;
        }

        public GoogleMapsCallDelta? GetDeltaGoogleMapsCall()
        {
            return Delta.GoogleMapsCallDelta;
        }

        public CodeExecutionResultDelta? GetDeltaCodeExecutionResult()
        {
            return Delta.CodeExecutionResultDelta;
        }

        public URLContextResultDelta? GetDeltaUrlContextResult()
        {
            return Delta.URLContextResultDelta;
        }

        public GoogleSearchResultDelta? GetDeltaGoogleSearchResult()
        {
            return Delta.GoogleSearchResultDelta;
        }

        public MCPServerToolResultDelta? GetDeltaMcpServerToolResult()
        {
            return Delta.MCPServerToolResultDelta;
        }

        public FileSearchResultDelta? GetDeltaFileSearchResult()
        {
            return Delta.FileSearchResultDelta;
        }

        public GoogleMapsResultDelta? GetDeltaGoogleMapsResult()
        {
            return Delta.GoogleMapsResultDelta;
        }

        public FunctionResultDelta? GetDeltaFunctionResult()
        {
            return Delta.FunctionResultDelta;
        }

        /// <summary>
        /// The event_id token to be used to resume the interaction stream, from<br/>
        /// this event.
        /// </summary>
        [JsonProperty("event_id")]
        public string? EventId { get; set; }

        /// <summary>
        /// Optional metadata accompanying ANY streamed event.
        /// </summary>
        [JsonProperty("metadata")]
        public StepDeltaMetadata? Metadata { get; set; }
    }
}