//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    public class StepDelta
    {
        [JsonProperty("delta", Required = Newtonsoft.Json.Required.Always, NullValueHandling = NullValueHandling.Include)]
        public StepDeltaData Delta { get; set; } = default!;

        public TextDelta? GetDeltaText()
        {
            return Delta.TextDelta;
        }

        public ImageDelta? GetDeltaImage()
        {
            return Delta.ImageDelta;
        }

        public AudioDelta? GetDeltaAudio()
        {
            return Delta.AudioDelta;
        }

        public DocumentDelta? GetDeltaDocument()
        {
            return Delta.DocumentDelta;
        }

        public VideoDelta? GetDeltaVideo()
        {
            return Delta.VideoDelta;
        }

        public ThoughtSummaryDelta? GetDeltaThoughtSummary()
        {
            return Delta.ThoughtSummaryDelta;
        }

        public ThoughtSignatureDelta? GetDeltaThoughtSignature()
        {
            return Delta.ThoughtSignatureDelta;
        }

        public TextAnnotationDelta? GetDeltaTextAnnotationDelta()
        {
            return Delta.TextAnnotationDelta;
        }

        public ArgumentsDelta? GetDeltaArgumentsDelta()
        {
            return Delta.ArgumentsDelta;
        }

        public CodeExecutionCallDelta? GetDeltaCodeExecutionCall()
        {
            return Delta.CodeExecutionCallDelta;
        }

        public URLContextCallDelta? GetDeltaUrlContextCall()
        {
            return Delta.URLContextCallDelta;
        }

        public GoogleSearchCallDelta? GetDeltaGoogleSearchCall()
        {
            return Delta.GoogleSearchCallDelta;
        }

        public MCPServerToolCallDelta? GetDeltaMcpServerToolCall()
        {
            return Delta.MCPServerToolCallDelta;
        }

        public FileSearchCallDelta? GetDeltaFileSearchCall()
        {
            return Delta.FileSearchCallDelta;
        }

        public GoogleMapsCallDelta? GetDeltaGoogleMapsCall()
        {
            return Delta.GoogleMapsCallDelta;
        }

        public RetrievalCallDelta? GetDeltaRetrievalCall()
        {
            return Delta.RetrievalCallDelta;
        }

        public CodeExecutionResultDelta? GetDeltaCodeExecutionResult()
        {
            return Delta.CodeExecutionResultDelta;
        }

        public URLContextResultDelta? GetDeltaUrlContextResult()
        {
            return Delta.URLContextResultDelta;
        }

        public GoogleSearchResultDelta? GetDeltaGoogleSearchResult()
        {
            return Delta.GoogleSearchResultDelta;
        }

        public MCPServerToolResultDelta? GetDeltaMcpServerToolResult()
        {
            return Delta.MCPServerToolResultDelta;
        }

        public FileSearchResultDelta? GetDeltaFileSearchResult()
        {
            return Delta.FileSearchResultDelta;
        }

        public GoogleMapsResultDelta? GetDeltaGoogleMapsResult()
        {
            return Delta.GoogleMapsResultDelta;
        }

        public RetrievalResultDelta? GetDeltaRetrievalResult()
        {
            return Delta.RetrievalResultDelta;
        }

        public FunctionResultDelta? GetDeltaFunctionResult()
        {
            return Delta.FunctionResultDelta;
        }

        /// <summary>
        /// The event_id token to be used to resume the interaction stream, from<br/>
        /// this event.
        /// </summary>
        [JsonProperty("event_id", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? EventId { get; set; }

        [JsonProperty("event_type", Required = Newtonsoft.Json.Required.Always)]
        public string EventType { get; } = "step.delta";

        [JsonProperty("index", Required = Newtonsoft.Json.Required.Always)]
        public int Index { get; set; } = default!;

        /// <summary>
        /// Optional metadata accompanying ANY streamed event.
        /// </summary>
        [JsonProperty("metadata", Required = Newtonsoft.Json.Required.DisallowNull)]
        public StepDeltaMetadata? Metadata { get; set; }
    }
}