// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Optional task mode for video generation. If not specified, the model<br/>
    /// automatically determines the appropriate mode based on the provided text<br/>
    /// prompt and input media.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class Task : IEquatable<Task>, IOpenEnum<string>
    {
        public static readonly Task TextToVideo = new Task("text_to_video");
        public static readonly Task ImageToVideo = new Task("image_to_video");
        public static readonly Task ReferenceToVideo = new Task("reference_to_video");
        public static readonly Task Edit = new Task("edit");
        public static readonly Task Extend = new Task("extend");

        private static readonly Dictionary<string, Task> _knownValues =
            new Dictionary<string, Task>() {
                ["text_to_video"] = TextToVideo,
                ["image_to_video"] = ImageToVideo,
                ["reference_to_video"] = ReferenceToVideo,
                ["edit"] = Edit,
                ["extend"] = Extend
            };

        private static readonly ConcurrentDictionary<string, Task> _values =
            new ConcurrentDictionary<string, Task>(_knownValues);

        private Task(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Task Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new Task(value));
        }

        public static implicit operator Task(string value) => Of(value);
        public static implicit operator string(Task task) => task.Value;

        public static Task[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Task);

        public bool Equals(Task? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}