//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The MIME type of the text output.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class TextResponseFormatMimeType : IEquatable<TextResponseFormatMimeType>, IOpenEnum<string>
    {
        public static readonly TextResponseFormatMimeType ApplicationJson = new TextResponseFormatMimeType("application/json");
        public static readonly TextResponseFormatMimeType TextPlain = new TextResponseFormatMimeType("text/plain");

        private static readonly Dictionary<string, TextResponseFormatMimeType> _knownValues =
            new Dictionary<string, TextResponseFormatMimeType>() {
                ["application/json"] = ApplicationJson,
                ["text/plain"] = TextPlain
            };

        private static readonly ConcurrentDictionary<string, TextResponseFormatMimeType> _values =
            new ConcurrentDictionary<string, TextResponseFormatMimeType>(_knownValues);

        private TextResponseFormatMimeType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static TextResponseFormatMimeType Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new TextResponseFormatMimeType(value));
        }

        public static implicit operator TextResponseFormatMimeType(string value) => Of(value);
        public static implicit operator string(TextResponseFormatMimeType textresponseformatmimetype) => textresponseformatmimetype.Value;

        public static TextResponseFormatMimeType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as TextResponseFormatMimeType);

        public bool Equals(TextResponseFormatMimeType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}