//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ThoughtSummaryContentType
    {
        private ThoughtSummaryContentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ThoughtSummaryContentType Text
        {
            get {
                return new ThoughtSummaryContentType("text");
            }
        }

        public static ThoughtSummaryContentType Image
        {
            get {
                return new ThoughtSummaryContentType("image");
            }
        }

        public static ThoughtSummaryContentType Unknown
        {
            get {
                return new ThoughtSummaryContentType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ThoughtSummaryContentType v)
        {
            return v.Value;
        }
        public static ThoughtSummaryContentType FromString(string v)
        {
            switch (v)
            {
                case "text":
                    return Text;
                case "image":
                    return Image;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for ThoughtSummaryContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ThoughtSummaryContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(ThoughtSummaryContent.ThoughtSummaryContentConverter))]
    public class ThoughtSummaryContent : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public ThoughtSummaryContent(ThoughtSummaryContentType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public TextContent? TextContent { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public ImageContent? ImageContent { get; set; }

        public ThoughtSummaryContentType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static ThoughtSummaryContent CreateUnknown(JToken raw)
        {
            return new ThoughtSummaryContent(ThoughtSummaryContentType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(ThoughtSummaryContentType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static ThoughtSummaryContent CreateText(TextContent text)
        {
            ThoughtSummaryContentType typ = ThoughtSummaryContentType.Text;
            ThoughtSummaryContent res = new ThoughtSummaryContent(typ);
            res.TextContent = text;
            return res;
        }

        public static ThoughtSummaryContent CreateImage(ImageContent image)
        {
            ThoughtSummaryContentType typ = ThoughtSummaryContentType.Image;
            ThoughtSummaryContent res = new ThoughtSummaryContent(typ);
            res.ImageContent = image;
            return res;
        }

        public class ThoughtSummaryContentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ThoughtSummaryContent);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken token = JToken.Load(reader);
                JObject? jo = token as JObject;
                if (jo == null)
                {
                    return CreateUnknown(token);
                }

                JToken? discriminatorToken = jo.GetValue("type");
                if (discriminatorToken == null || discriminatorToken.Type != JTokenType.String)
                {
                    return CreateUnknown(jo);
                }

                string discriminator = discriminatorToken.ToString();
                if (discriminator == ThoughtSummaryContentType.Text.ToString())
                {
                    TextContent textContent;
                    try
                    {
                        textContent = ResponseBodyDeserializer.DeserializeNotNull<TextContent>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<TextContent>(jo.ToString(), out textContent))
                        {
                            throw;
                        }
                    }
                    return CreateText(textContent);
                }
                if (discriminator == ThoughtSummaryContentType.Image.ToString())
                {
                    ImageContent imageContent;
                    try
                    {
                        imageContent = ResponseBodyDeserializer.DeserializeNotNull<ImageContent>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<ImageContent>(jo.ToString(), out imageContent))
                        {
                            throw;
                        }
                    }
                    return CreateImage(imageContent);
                }

                return CreateUnknown(jo);
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ThoughtSummaryContent res = (ThoughtSummaryContent)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.TextContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TextContent));
                    return;
                }

                if (res.ImageContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ImageContent));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}