//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Required. The threshold for blocking content. If the harm probability<br/>
    /// exceeds this threshold, the content will be blocked.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class Threshold : IEquatable<Threshold>, IOpenEnum<string>
    {
        public static readonly Threshold BlockLowAndAbove = new Threshold("block_low_and_above");
        public static readonly Threshold BlockMediumAndAbove = new Threshold("block_medium_and_above");
        public static readonly Threshold BlockOnlyHigh = new Threshold("block_only_high");
        public static readonly Threshold BlockNone = new Threshold("block_none");
        public static readonly Threshold Off = new Threshold("off");

        private static readonly Dictionary<string, Threshold> _knownValues =
            new Dictionary<string, Threshold>() {
                ["block_low_and_above"] = BlockLowAndAbove,
                ["block_medium_and_above"] = BlockMediumAndAbove,
                ["block_only_high"] = BlockOnlyHigh,
                ["block_none"] = BlockNone,
                ["off"] = Off
            };

        private static readonly ConcurrentDictionary<string, Threshold> _values =
            new ConcurrentDictionary<string, Threshold>(_knownValues);

        private Threshold(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Threshold Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new Threshold(value));
        }

        public static implicit operator Threshold(string value) => Of(value);
        public static implicit operator string(Threshold threshold) => threshold.Value;

        public static Threshold[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Threshold);

        public bool Equals(Threshold? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}