//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ToolType
    {
        private ToolType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ToolType CodeExecution
        {
            get {
                return new ToolType("code_execution");
            }
        }

        public static ToolType ComputerUse
        {
            get {
                return new ToolType("computer_use");
            }
        }

        public static ToolType FileSearch
        {
            get {
                return new ToolType("file_search");
            }
        }

        public static ToolType Function
        {
            get {
                return new ToolType("function");
            }
        }

        public static ToolType GoogleMaps
        {
            get {
                return new ToolType("google_maps");
            }
        }

        public static ToolType GoogleSearch
        {
            get {
                return new ToolType("google_search");
            }
        }

        public static ToolType McpServer
        {
            get {
                return new ToolType("mcp_server");
            }
        }

        public static ToolType Retrieval
        {
            get {
                return new ToolType("retrieval");
            }
        }

        public static ToolType UrlContext
        {
            get {
                return new ToolType("url_context");
            }
        }

        public static ToolType Unknown
        {
            get {
                return new ToolType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ToolType v)
        {
            return v.Value;
        }
        public static ToolType FromString(string v)
        {
            switch (v)
            {
                case "code_execution":
                    return CodeExecution;
                case "computer_use":
                    return ComputerUse;
                case "file_search":
                    return FileSearch;
                case "function":
                    return Function;
                case "google_maps":
                    return GoogleMaps;
                case "google_search":
                    return GoogleSearch;
                case "mcp_server":
                    return McpServer;
                case "retrieval":
                    return Retrieval;
                case "url_context":
                    return UrlContext;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for ToolType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ToolType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// A tool that can be used by the model.
    /// </summary>
    [JsonConverter(typeof(Tool.ToolConverter))]
    public class Tool : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public Tool(ToolType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public CodeExecution? CodeExecution { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public ComputerUse? ComputerUse { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public FileSearch? FileSearch { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Function? Function { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public GoogleMaps? GoogleMaps { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public GoogleSearch? GoogleSearch { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public MCPServer? MCPServer { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Retrieval? Retrieval { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public URLContext? URLContext { get; set; }

        public ToolType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static Tool CreateUnknown(JToken raw)
        {
            return new Tool(ToolType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(ToolType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static Tool CreateCodeExecution(CodeExecution codeExecution)
        {
            ToolType typ = ToolType.CodeExecution;
            Tool res = new Tool(typ);
            res.CodeExecution = codeExecution;
            return res;
        }

        public static Tool CreateComputerUse(ComputerUse computerUse)
        {
            ToolType typ = ToolType.ComputerUse;
            Tool res = new Tool(typ);
            res.ComputerUse = computerUse;
            return res;
        }

        public static Tool CreateFileSearch(FileSearch fileSearch)
        {
            ToolType typ = ToolType.FileSearch;
            Tool res = new Tool(typ);
            res.FileSearch = fileSearch;
            return res;
        }

        public static Tool CreateFunction(Function function)
        {
            ToolType typ = ToolType.Function;
            Tool res = new Tool(typ);
            res.Function = function;
            return res;
        }

        public static Tool CreateGoogleMaps(GoogleMaps googleMaps)
        {
            ToolType typ = ToolType.GoogleMaps;
            Tool res = new Tool(typ);
            res.GoogleMaps = googleMaps;
            return res;
        }

        public static Tool CreateGoogleSearch(GoogleSearch googleSearch)
        {
            ToolType typ = ToolType.GoogleSearch;
            Tool res = new Tool(typ);
            res.GoogleSearch = googleSearch;
            return res;
        }

        public static Tool CreateMcpServer(MCPServer mcpServer)
        {
            ToolType typ = ToolType.McpServer;
            Tool res = new Tool(typ);
            res.MCPServer = mcpServer;
            return res;
        }

        public static Tool CreateRetrieval(Retrieval retrieval)
        {
            ToolType typ = ToolType.Retrieval;
            Tool res = new Tool(typ);
            res.Retrieval = retrieval;
            return res;
        }

        public static Tool CreateUrlContext(URLContext urlContext)
        {
            ToolType typ = ToolType.UrlContext;
            Tool res = new Tool(typ);
            res.URLContext = urlContext;
            return res;
        }

        public class ToolConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Tool);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken token = JToken.Load(reader);
                JObject? jo = token as JObject;
                if (jo == null)
                {
                    return CreateUnknown(token);
                }

                JToken? discriminatorToken = jo.GetValue("type");
                if (discriminatorToken == null || discriminatorToken.Type != JTokenType.String)
                {
                    return CreateUnknown(jo);
                }

                string discriminator = discriminatorToken.ToString();
                if (discriminator == ToolType.CodeExecution.ToString())
                {
                    CodeExecution codeExecution;
                    try
                    {
                        codeExecution = ResponseBodyDeserializer.DeserializeNotNull<CodeExecution>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<CodeExecution>(jo.ToString(), out codeExecution))
                        {
                            throw;
                        }
                    }
                    return CreateCodeExecution(codeExecution);
                }
                if (discriminator == ToolType.ComputerUse.ToString())
                {
                    ComputerUse computerUse;
                    try
                    {
                        computerUse = ResponseBodyDeserializer.DeserializeNotNull<ComputerUse>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<ComputerUse>(jo.ToString(), out computerUse))
                        {
                            throw;
                        }
                    }
                    return CreateComputerUse(computerUse);
                }
                if (discriminator == ToolType.FileSearch.ToString())
                {
                    FileSearch fileSearch;
                    try
                    {
                        fileSearch = ResponseBodyDeserializer.DeserializeNotNull<FileSearch>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<FileSearch>(jo.ToString(), out fileSearch))
                        {
                            throw;
                        }
                    }
                    return CreateFileSearch(fileSearch);
                }
                if (discriminator == ToolType.Function.ToString())
                {
                    Function function;
                    try
                    {
                        function = ResponseBodyDeserializer.DeserializeNotNull<Function>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<Function>(jo.ToString(), out function))
                        {
                            throw;
                        }
                    }
                    return CreateFunction(function);
                }
                if (discriminator == ToolType.GoogleMaps.ToString())
                {
                    GoogleMaps googleMaps;
                    try
                    {
                        googleMaps = ResponseBodyDeserializer.DeserializeNotNull<GoogleMaps>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<GoogleMaps>(jo.ToString(), out googleMaps))
                        {
                            throw;
                        }
                    }
                    return CreateGoogleMaps(googleMaps);
                }
                if (discriminator == ToolType.GoogleSearch.ToString())
                {
                    GoogleSearch googleSearch;
                    try
                    {
                        googleSearch = ResponseBodyDeserializer.DeserializeNotNull<GoogleSearch>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<GoogleSearch>(jo.ToString(), out googleSearch))
                        {
                            throw;
                        }
                    }
                    return CreateGoogleSearch(googleSearch);
                }
                if (discriminator == ToolType.McpServer.ToString())
                {
                    MCPServer mcpServer;
                    try
                    {
                        mcpServer = ResponseBodyDeserializer.DeserializeNotNull<MCPServer>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<MCPServer>(jo.ToString(), out mcpServer))
                        {
                            throw;
                        }
                    }
                    return CreateMcpServer(mcpServer);
                }
                if (discriminator == ToolType.Retrieval.ToString())
                {
                    Retrieval retrieval;
                    try
                    {
                        retrieval = ResponseBodyDeserializer.DeserializeNotNull<Retrieval>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<Retrieval>(jo.ToString(), out retrieval))
                        {
                            throw;
                        }
                    }
                    return CreateRetrieval(retrieval);
                }
                if (discriminator == ToolType.UrlContext.ToString())
                {
                    URLContext urlContext;
                    try
                    {
                        urlContext = ResponseBodyDeserializer.DeserializeNotNull<URLContext>(jo.ToString());
                    }
                    catch (Exception)
                    {
                        if (!ResponseBodyDeserializer.TryConstructUnvalidated<URLContext>(jo.ToString(), out urlContext))
                        {
                            throw;
                        }
                    }
                    return CreateUrlContext(urlContext);
                }

                return CreateUnknown(jo);
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Tool res = (Tool)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.CodeExecution != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CodeExecution));
                    return;
                }

                if (res.ComputerUse != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ComputerUse));
                    return;
                }

                if (res.FileSearch != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.FileSearch));
                    return;
                }

                if (res.Function != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Function));
                    return;
                }

                if (res.GoogleMaps != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GoogleMaps));
                    return;
                }

                if (res.GoogleSearch != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GoogleSearch));
                    return;
                }

                if (res.MCPServer != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MCPServer));
                    return;
                }

                if (res.Retrieval != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Retrieval));
                    return;
                }

                if (res.URLContext != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.URLContext));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}