// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class TransformType
    {
        private TransformType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static TransformType MapOfStr
        {
            get {
                return new TransformType("mapOfStr");
            }
        }

        public static TransformType ArrayOfMapOfStr
        {
            get {
                return new TransformType("arrayOfMapOfStr");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(TransformType v)
        {
            return v.Value;
        }
        public static TransformType FromString(string v)
        {
            switch (v)
            {
                case "mapOfStr":
                    return MapOfStr;
                case "arrayOfMapOfStr":
                    return ArrayOfMapOfStr;
                default:
                    throw new ArgumentException("Invalid value for TransformType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TransformType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
    /// </summary>
    [JsonConverter(typeof(Transform.TransformConverter))]
    public class Transform
    {
        public Transform(TransformType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, string>? MapOfStr { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<Dictionary<string, string>>? ArrayOfMapOfStr { get; set; }

        public TransformType Type { get; set; }
        public static Transform CreateMapOfStr(Dictionary<string, string> mapOfStr)
        {
            TransformType typ = TransformType.MapOfStr;

            Transform res = new Transform(typ);
            res.MapOfStr = mapOfStr;
            return res;
        }
        public static Transform CreateArrayOfMapOfStr(List<Dictionary<string, string>> arrayOfMapOfStr)
        {
            TransformType typ = TransformType.ArrayOfMapOfStr;

            Transform res = new Transform(typ);
            res.ArrayOfMapOfStr = arrayOfMapOfStr;
            return res;
        }

        public class TransformConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Transform);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Transform(TransformType.MapOfStr) {
                        MapOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, string>), new Transform(TransformType.MapOfStr), "MapOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Transform(TransformType.ArrayOfMapOfStr) {
                        ArrayOfMapOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<Dictionary<string, string>>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<Dictionary<string, string>>), new Transform(TransformType.ArrayOfMapOfStr), "ArrayOfMapOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Transform res = (Transform)value;

                if (res.MapOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfStr));
                    return;
                }

                if (res.ArrayOfMapOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfMapOfStr));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}