//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class TransformType
    {
        private TransformType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static TransformType MapOfStr
        {
            get {
                return new TransformType("mapOfStr");
            }
        }

        public static TransformType ArrayOfMapOfStr
        {
            get {
                return new TransformType("arrayOfMapOfStr");
            }
        }

        public static TransformType Unknown
        {
            get {
                return new TransformType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(TransformType v)
        {
            return v.Value;
        }
        public static TransformType FromString(string v)
        {
            switch (v)
            {
                case "mapOfStr":
                    return MapOfStr;
                case "arrayOfMapOfStr":
                    return ArrayOfMapOfStr;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for TransformType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TransformType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
    /// </summary>
    [JsonConverter(typeof(Transform.TransformConverter))]
    public class Transform : Google.GenAI.Gaos.Utils.IOpenUnion
    {
        public Transform(TransformType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, string>? MapOfStr { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public List<Dictionary<string, string>>? ArrayOfMapOfStr { get; set; }

        public TransformType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static Transform CreateUnknown(JToken raw)
        {
            return new Transform(TransformType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(TransformType.Unknown);
        }

        bool Google.GenAI.Gaos.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static Transform CreateMapOfStr(Dictionary<string, string> mapOfStr)
        {
            TransformType typ = TransformType.MapOfStr;

            Transform res = new Transform(typ);
            res.MapOfStr = mapOfStr;
            return res;
        }
        public static Transform CreateArrayOfMapOfStr(List<Dictionary<string, string>> arrayOfMapOfStr)
        {
            TransformType typ = TransformType.ArrayOfMapOfStr;

            Transform res = new Transform(typ);
            res.ArrayOfMapOfStr = arrayOfMapOfStr;
            return res;
        }

        public class TransformConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Transform);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<TransformType>();
                unionCandidates.Add<Dictionary<string, string>>("MapOfStr", 0, TransformType.MapOfStr);
                unionCandidates.Add<List<Dictionary<string, string>>>("ArrayOfMapOfStr", 1, TransformType.ArrayOfMapOfStr);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    return CreateUnknown(jt);
                }

                var result = new Transform(winner.TypeName);
                typeof(Transform).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Transform res = (Transform)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.MapOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfStr));
                    return;
                }

                if (res.ArrayOfMapOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfMapOfStr));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}