//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;

    [Obsolete("This will be removed in a future release, please migrate away from it as soon as possible")]
    public class Turn
    {
        [JsonProperty("content", Required = Newtonsoft.Json.Required.DisallowNull)]
        public TurnContent? Content { get; set; }

        /// <summary>
        /// The originator of this turn. Must be user for input or model for<br/>
        /// model output.
        /// </summary>
        [JsonProperty("role", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Role { get; set; }
    }
}