// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class TurnContentType
    {
        private TurnContentType(string value) { Value = value; }

        public string Value { get; private set; }

        public static TurnContentType ArrayOfContent { get { return new TurnContentType("arrayOfContent"); } }

        public static TurnContentType Str { get { return new TurnContentType("str"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(TurnContentType v) { return v.Value; }
        public static TurnContentType FromString(string v) {
            switch(v) {
                case "arrayOfContent": return ArrayOfContent;
                case "str": return Str;
                default: throw new ArgumentException("Invalid value for TurnContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TurnContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(TurnContent.TurnContentConverter))]
    public class TurnContent
    {
        public TurnContent(TurnContentType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public List<Content>? ArrayOfContent { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        public TurnContentType Type { get; set; }
        public static TurnContent CreateArrayOfContent(List<Content> arrayOfContent)
        {
            TurnContentType typ = TurnContentType.ArrayOfContent;

            TurnContent res = new TurnContent(typ);
            res.ArrayOfContent = arrayOfContent;
            return res;
        }
        public static TurnContent CreateStr(string str)
        {
            TurnContentType typ = TurnContentType.Str;

            TurnContent res = new TurnContent(typ);
            res.Str = str;
            return res;
        }

        public class TurnContentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(TurnContent);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new TurnContent(TurnContentType.ArrayOfContent)
                    {
                        ArrayOfContent = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<Content>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<Content>), new TurnContent(TurnContentType.ArrayOfContent), "ArrayOfContent"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new TurnContent(TurnContentType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                TurnContent res = (TurnContent)value;

                if (res.ArrayOfContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfContent));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}