//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// A URL citation annotation.
    /// </summary>
    public class URLCitation
    {
        /// <summary>
        /// End of the attributed segment, exclusive.
        /// </summary>
        [JsonProperty("end_index", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? EndIndex { get; set; }

        /// <summary>
        /// Start of segment of the response that is attributed to this source.<br/>
        /// <br/>
        /// Index indicates the start of the segment, measured in bytes.
        /// </summary>
        [JsonProperty("start_index", Required = Newtonsoft.Json.Required.DisallowNull)]
        public int? StartIndex { get; set; }

        /// <summary>
        /// The title of the URL.
        /// </summary>
        [JsonProperty("title", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Title { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "url_citation";

        /// <summary>
        /// The URL.
        /// </summary>
        [JsonProperty("url", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Url { get; set; }
    }
}