//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class VideoDelta
    {
        [JsonProperty("data", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Data { get; set; }

        [JsonProperty("mime_type", Required = Newtonsoft.Json.Required.DisallowNull)]
        public VideoDeltaMimeType? MimeType { get; set; }

        [JsonProperty("resolution", Required = Newtonsoft.Json.Required.DisallowNull)]
        public MediaResolution? Resolution { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "video";

        [JsonProperty("uri", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Uri { get; set; }
    }
}