// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A video content block.
    /// </summary>
    public class VideoContent
    {
        /// <summary>
        /// The video content.
        /// </summary>
        [JsonProperty("data")]
        public string? Data { get; set; }

        /// <summary>
        /// The mime type of the video.
        /// </summary>
        [JsonProperty("mime_type")]
        public VideoContentMimeType? MimeType { get; set; }

        /// <summary>
        /// A user-defined name for this content block. Can be referenced by the model<br/>
        /// in the final response.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// How the model processes this video for understanding.
        /// </summary>
        [JsonProperty("processing", NullValueHandling = NullValueHandling.Include)]
        public Processing? Processing { get; set; }

        [JsonProperty("resolution")]
        public MediaResolution? Resolution { get; set; }

        [JsonProperty("type")]
        public string Type { get; } = "video";

        /// <summary>
        /// The URI of the video.
        /// </summary>
        [JsonProperty("uri")]
        public string? Uri { get; set; }
    }
}