//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Configuration for video output format.
    /// </summary>
    public class VideoResponseFormat
    {
        /// <summary>
        /// The aspect ratio for the video output.
        /// </summary>
        [JsonProperty("aspect_ratio", Required = Newtonsoft.Json.Required.DisallowNull)]
        public VideoResponseFormatAspectRatio? AspectRatio { get; set; }

        /// <summary>
        /// The delivery mode for the video output.
        /// </summary>
        [JsonProperty("delivery", Required = Newtonsoft.Json.Required.DisallowNull)]
        public VideoResponseFormatDelivery? Delivery { get; set; }

        /// <summary>
        /// The duration for the video output.
        /// </summary>
        [JsonProperty("duration", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Duration { get; set; }

        /// <summary>
        /// The Cloud Storage URI to store the video output. Required for Vertex if<br/>
        /// delivery mode is URI.
        /// </summary>
        [JsonProperty("gcs_uri", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? GcsUri { get; set; }

        /// <summary>
        /// The video output resolution. Defaults to 720p.
        /// </summary>
        [JsonProperty("resolution", Required = Newtonsoft.Json.Required.DisallowNull)]
        public Resolution? Resolution { get; set; }

        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; } = "video";
    }
}