//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Interactions
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Whether to include visualizations in the response.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class Visualization : IEquatable<Visualization>, IOpenEnum<string>
    {
        public static readonly Visualization Off = new Visualization("off");
        public static readonly Visualization Auto = new Visualization("auto");

        private static readonly Dictionary<string, Visualization> _knownValues =
            new Dictionary<string, Visualization>() {
                ["off"] = Off,
                ["auto"] = Auto
            };

        private static readonly ConcurrentDictionary<string, Visualization> _values =
            new ConcurrentDictionary<string, Visualization>(_knownValues);

        private Visualization(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Visualization Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new Visualization(value));
        }

        public static implicit operator Visualization(string value) => Of(value);
        public static implicit operator string(Visualization visualization) => visualization.Value;

        public static Visualization[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Visualization);

        public bool Equals(Visualization? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}