//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Triggers
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Optional. The status of the trigger.
    /// </summary>
    public enum TriggerUpdateStatus
    {
        [JsonProperty("active")] Active,
        [JsonProperty("paused")] Paused,
        [JsonProperty("error")] Error,
    }

    public static class TriggerUpdateStatusExtension
    {
        public static string Value(this TriggerUpdateStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TriggerUpdateStatus ToEnum(this string value)
        {
            foreach (var field in typeof(TriggerUpdateStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TriggerUpdateStatus)
                    {
                        return (TriggerUpdateStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TriggerUpdateStatus");
        }
    }
}