//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Triggers
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Output only. The status of the execution.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class TriggerExecutionStatus : IEquatable<TriggerExecutionStatus>, IOpenEnum<string>
    {
        public static readonly TriggerExecutionStatus InProgress = new TriggerExecutionStatus("in_progress");
        public static readonly TriggerExecutionStatus Completed = new TriggerExecutionStatus("completed");
        public static readonly TriggerExecutionStatus Failed = new TriggerExecutionStatus("failed");
        public static readonly TriggerExecutionStatus Skipped = new TriggerExecutionStatus("skipped");
        public static readonly TriggerExecutionStatus TimedOut = new TriggerExecutionStatus("timed_out");

        private static readonly Dictionary<string, TriggerExecutionStatus> _knownValues =
            new Dictionary<string, TriggerExecutionStatus>() {
                ["in_progress"] = InProgress,
                ["completed"] = Completed,
                ["failed"] = Failed,
                ["skipped"] = Skipped,
                ["timed_out"] = TimedOut
            };

        private static readonly ConcurrentDictionary<string, TriggerExecutionStatus> _values =
            new ConcurrentDictionary<string, TriggerExecutionStatus>(_knownValues);

        private TriggerExecutionStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static TriggerExecutionStatus Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new TriggerExecutionStatus(value));
        }

        public static implicit operator TriggerExecutionStatus(string value) => Of(value);
        public static implicit operator string(TriggerExecutionStatus triggerexecutionstatus) => triggerexecutionstatus.Value;

        public static TriggerExecutionStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as TriggerExecutionStatus);

        public bool Equals(TriggerExecutionStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}