// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Triggers
{
    using Google.GenAI.Gaos.Models.Triggers;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// A trigger configuration that is scheduled to run an agent.
    /// </summary>
    public class Trigger
    {
        /// <summary>
        /// Output only. The number of consecutive failures that have occurred<br/>
        /// since the last successful execution.
        /// </summary>
        [JsonProperty("consecutive_failure_count")]
        public int? ConsecutiveFailureCount { get; set; }

        /// <summary>
        /// Output only. The time when the trigger was created.
        /// </summary>
        [JsonProperty("create_time")]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// Optional. The display name of the trigger.
        /// </summary>
        [JsonProperty("display_name")]
        public string? DisplayName { get; set; }

        /// <summary>
        /// Optional. The environment ID for the trigger execution.
        /// </summary>
        [JsonProperty("environment_id")]
        public string? EnvironmentId { get; set; }

        /// <summary>
        /// Optional. The execution timeout for the triggered interaction.
        /// </summary>
        [JsonProperty("execution_timeout_seconds")]
        public int? ExecutionTimeoutSeconds { get; set; }

        /// <summary>
        /// Required. Output only. Identifier. The ID of the trigger.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Configuration parameters for the interaction request template.
        /// </summary>
        [JsonProperty("interaction")]
        public TriggerInteractionRequest Interaction { get; set; } = default!;

        /// <summary>
        /// Output only. The time when the trigger was last paused.
        /// </summary>
        [JsonProperty("last_pause_time")]
        public DateTime? LastPauseTime { get; set; }

        /// <summary>
        /// Output only. The time when the trigger was last resumed.
        /// </summary>
        [JsonProperty("last_resume_time")]
        public DateTime? LastResumeTime { get; set; }

        /// <summary>
        /// Output only. The time when the trigger was last run.
        /// </summary>
        [JsonProperty("last_run_time")]
        public DateTime? LastRunTime { get; set; }

        /// <summary>
        /// Optional. The maximum number of consecutive failures allowed before<br/>
        /// the trigger is automatically paused (status becomes ERROR).
        /// </summary>
        [JsonProperty("max_consecutive_failures")]
        public int? MaxConsecutiveFailures { get; set; }

        /// <summary>
        /// Output only. The time when the trigger is scheduled to run next.
        /// </summary>
        [JsonProperty("next_run_time")]
        public DateTime? NextRunTime { get; set; }

        /// <summary>
        /// Output only. The ID of the last interaction created by this trigger.
        /// </summary>
        [JsonProperty("previous_interaction_id")]
        public string? PreviousInteractionId { get; set; }

        /// <summary>
        /// Required. The cron schedule on which the trigger should run.<br/>
        /// Standard cron format.
        /// </summary>
        [JsonProperty("schedule")]
        public string Schedule { get; set; } = default!;

        /// <summary>
        /// Output only. The current status of the trigger.
        /// </summary>
        [JsonProperty("status")]
        public TriggerStatus? Status { get; set; }

        /// <summary>
        /// Required. Time zone in which the schedule should be interpreted.
        /// </summary>
        [JsonProperty("time_zone")]
        public string TimeZone { get; set; } = default!;

        /// <summary>
        /// Output only. The time when the trigger was last updated.
        /// </summary>
        [JsonProperty("update_time")]
        public DateTime? UpdateTime { get; set; }
    }
}