// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Requests
{
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CreateInteractionRequestBodyType
    {
        private CreateInteractionRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }

        public static CreateInteractionRequestBodyType CreateModelInteraction { get { return new CreateInteractionRequestBodyType("CreateModelInteraction"); } }

        public static CreateInteractionRequestBodyType CreateAgentInteraction { get { return new CreateInteractionRequestBodyType("CreateAgentInteraction"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CreateInteractionRequestBodyType v) { return v.Value; }
        public static CreateInteractionRequestBodyType FromString(string v) {
            switch(v) {
                case "CreateModelInteraction": return CreateModelInteraction;
                case "CreateAgentInteraction": return CreateAgentInteraction;
                default: throw new ArgumentException("Invalid value for CreateInteractionRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateInteractionRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The request body.
    /// </summary>
    [JsonConverter(typeof(CreateInteractionRequestBody.CreateInteractionRequestBodyConverter))]
    public class CreateInteractionRequestBody
    {
        public CreateInteractionRequestBody(CreateInteractionRequestBodyType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public CreateModelInteraction? CreateModelInteraction { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public CreateAgentInteraction? CreateAgentInteraction { get; set; }

        public CreateInteractionRequestBodyType Type { get; set; }
        public static CreateInteractionRequestBody CreateCreateModelInteraction(CreateModelInteraction createModelInteraction)
        {
            CreateInteractionRequestBodyType typ = CreateInteractionRequestBodyType.CreateModelInteraction;

            CreateInteractionRequestBody res = new CreateInteractionRequestBody(typ);
            res.CreateModelInteraction = createModelInteraction;
            return res;
        }
        public static CreateInteractionRequestBody CreateCreateAgentInteraction(CreateAgentInteraction createAgentInteraction)
        {
            CreateInteractionRequestBodyType typ = CreateInteractionRequestBodyType.CreateAgentInteraction;

            CreateInteractionRequestBody res = new CreateInteractionRequestBody(typ);
            res.CreateAgentInteraction = createAgentInteraction;
            return res;
        }

        public class CreateInteractionRequestBodyConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateInteractionRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CreateInteractionRequestBody(CreateInteractionRequestBodyType.CreateAgentInteraction)
                    {
                        CreateAgentInteraction = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CreateAgentInteraction>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CreateAgentInteraction), new CreateInteractionRequestBody(CreateInteractionRequestBodyType.CreateAgentInteraction), "CreateAgentInteraction"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CreateInteractionRequestBody(CreateInteractionRequestBodyType.CreateModelInteraction)
                    {
                        CreateModelInteraction = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CreateModelInteraction>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CreateModelInteraction), new CreateInteractionRequestBody(CreateInteractionRequestBodyType.CreateModelInteraction), "CreateModelInteraction"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CreateInteractionRequestBody res = (CreateInteractionRequestBody)value;

                if (res.CreateModelInteraction != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CreateModelInteraction));
                    return;
                }

                if (res.CreateAgentInteraction != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CreateAgentInteraction));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}