//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Requests
{
    using Google.GenAI.Gaos.Utils;

    public class GetEnvironmentRequest
    {
        /// <summary>
        /// Which version of the API to use.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=api_version")]
        public string? ApiVersion { get; set; }

        /// <summary>
        /// Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;
    }
}