//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Requests
{
    using Google.GenAI.Gaos.Utils;

    public class ListTriggerExecutionsRequest
    {
        /// <summary>
        /// Which version of the API to use.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=api_version")]
        public string? ApiVersion { get; set; }

        /// <summary>
        /// Resource name of the trigger.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=trigger_id")]
        public string TriggerId { get; set; } = default!;

        /// <summary>
        /// Optional. The maximum number of executions to return per page.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")]
        public long? PageSize { get; set; }

        /// <summary>
        /// Optional. A page token from a previous ListTriggerExecutions call.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_token")]
        public string? PageToken { get; set; }
    }
}