//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Requests
{
    using Google.GenAI.Gaos.Models.Webhooks;
    using Google.GenAI.Gaos.Utils;

    public class PingWebhookRequest
    {
        /// <summary>
        /// Which version of the API to use.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=api_version")]
        public string? ApiVersion { get; set; }

        /// <summary>
        /// Required. The ID of the webhook to ping.<br/>
        /// Format: `{webhook_id}`
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The request body.
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public Models.Webhooks.PingWebhookRequest? Body { get; set; }
    }
}