//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Requests
{
    using Google.GenAI.Gaos.Models.Webhooks;
    using Google.GenAI.Gaos.Utils;

    public class UpdateWebhookRequest
    {
        /// <summary>
        /// Which version of the API to use.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=api_version")]
        public string? ApiVersion { get; set; }

        /// <summary>
        /// Required. The ID of the webhook to update.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Optional. The list of fields to update.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=update_mask")]
        public string? UpdateMask { get; set; }

        /// <summary>
        /// Required. The webhook to update.
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public WebhookUpdate? Body { get; set; }
    }
}