using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

using Google.GenAI.Types;

namespace Google.GenAI
{
  [JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = true)]
  [JsonSerializable(typeof(BatchJob))]
  [JsonSerializable(typeof(Blob))]
  [JsonSerializable(typeof(CachedContent))]
  [JsonSerializable(typeof(CancelBatchJobParameters))]
  [JsonSerializable(typeof(CancelTuningJobParameters))]
  [JsonSerializable(typeof(CancelTuningJobResponse))]
  [JsonSerializable(typeof(ComputeTokensParameters))]
  [JsonSerializable(typeof(ComputeTokensResponse))]
  [JsonSerializable(typeof(Content))]
  [JsonSerializable(typeof(CountTokensParameters))]
  [JsonSerializable(typeof(CountTokensResponse))]
  [JsonSerializable(typeof(CreateBatchJobParameters))]
  [JsonSerializable(typeof(CreateCachedContentParameters))]
  [JsonSerializable(typeof(CreateEmbeddingsBatchJobParameters))]
  [JsonSerializable(typeof(CreateFileParameters))]
  [JsonSerializable(typeof(CreateFileResponse))]
  [JsonSerializable(typeof(CreateTuningJobParametersPrivate))]
  [JsonSerializable(typeof(DeleteBatchJobParameters))]
  [JsonSerializable(typeof(DeleteCachedContentParameters))]
  [JsonSerializable(typeof(DeleteCachedContentResponse))]
  [JsonSerializable(typeof(DeleteFileParameters))]
  [JsonSerializable(typeof(DeleteFileResponse))]
  [JsonSerializable(typeof(DeleteModelParameters))]
  [JsonSerializable(typeof(DeleteModelResponse))]
  [JsonSerializable(typeof(DeleteResourceJob))]
  [JsonSerializable(typeof(EditImageParameters))]
  [JsonSerializable(typeof(EditImageResponse))]
  [JsonSerializable(typeof(EmbedContentParametersPrivate))]
  [JsonSerializable(typeof(EmbedContentResponse))]
  [JsonSerializable(typeof(FetchPredictOperationParameters))]
  [JsonSerializable(typeof(GenerateContentParameters))]
  [JsonSerializable(typeof(GenerateContentResponse))]
  [JsonSerializable(typeof(GenerateImagesParameters))]
  [JsonSerializable(typeof(GenerateImagesResponse))]
  [JsonSerializable(typeof(GenerateVideosOperation))]
  [JsonSerializable(typeof(GenerateVideosParameters))]
  [JsonSerializable(typeof(GenerateVideosResponse))]
  [JsonSerializable(typeof(GetBatchJobParameters))]
  [JsonSerializable(typeof(GetCachedContentParameters))]
  [JsonSerializable(typeof(GetFileParameters))]
  [JsonSerializable(typeof(GetModelParameters))]
  [JsonSerializable(typeof(GetOperationParameters))]
  [JsonSerializable(typeof(GetTuningJobParameters))]
  [JsonSerializable(typeof(InternalRegisterFilesParameters))]
  [JsonSerializable(typeof(ListBatchJobsResponse))]
  [JsonSerializable(typeof(ListCachedContentsParameters))]
  [JsonSerializable(typeof(ListCachedContentsResponse))]
  [JsonSerializable(typeof(ListFilesParameters))]
  [JsonSerializable(typeof(ListFilesResponse))]
  [JsonSerializable(typeof(ListModelsParameters))]
  [JsonSerializable(typeof(ListModelsResponse))]
  [JsonSerializable(typeof(ListTuningJobsParameters))]
  [JsonSerializable(typeof(ListTuningJobsResponse))]
  [JsonSerializable(typeof(LiveClientContent))]
  [JsonSerializable(typeof(LiveClientMessage))]
  [JsonSerializable(typeof(LiveClientRealtimeInput))]
  [JsonSerializable(typeof(LiveClientSetup))]
  [JsonSerializable(typeof(LiveClientToolResponse))]
  [JsonSerializable(typeof(LiveConnectConfig))]
  [JsonSerializable(typeof(LiveConnectParameters))]
  [JsonSerializable(typeof(LiveSendClientContentParameters))]
  [JsonSerializable(typeof(LiveSendRealtimeInputParameters))]
  [JsonSerializable(typeof(LiveSendToolResponseParameters))]
  [JsonSerializable(typeof(LiveServerContent))]
  [JsonSerializable(typeof(LiveServerGoAway))]
  [JsonSerializable(typeof(LiveServerMessage))]
  [JsonSerializable(typeof(LiveServerSessionResumptionUpdate))]
  [JsonSerializable(typeof(LiveServerSetupComplete))]
  [JsonSerializable(typeof(LiveServerToolCall))]
  [JsonSerializable(typeof(LiveServerToolCallCancellation))]
  [JsonSerializable(typeof(Model))]
  [JsonSerializable(typeof(RealtimeInputConfig))]
  [JsonSerializable(typeof(RecontextImageParameters))]
  [JsonSerializable(typeof(RecontextImageResponse))]
  [JsonSerializable(typeof(RegisterFilesResponse))]
  [JsonSerializable(typeof(Schema))]
  [JsonSerializable(typeof(SegmentImageParameters))]
  [JsonSerializable(typeof(SegmentImageResponse))]
  [JsonSerializable(typeof(SpeechConfig))]
  [JsonSerializable(typeof(Tool))]
  [JsonSerializable(typeof(TuningJob))]
  [JsonSerializable(typeof(TuningOperation))]
  [JsonSerializable(typeof(UpdateCachedContentParameters))]
  [JsonSerializable(typeof(UpdateModelParameters))]
  [JsonSerializable(typeof(UpscaleImageAPIParameters))]
  [JsonSerializable(typeof(UpscaleImageResponse))]
  [JsonSerializable(typeof(Google.GenAI.Types.File))]
  [JsonSerializable(typeof(List<Content>))]
  [JsonSerializable(typeof(List<Tool>))]
  [JsonSerializable(typeof(string))]
  [JsonSerializable(typeof(System.Text.Json.Nodes.JsonNode))]
  [JsonSerializable(typeof(System.Text.Json.Nodes.JsonObject))]
  [JsonSerializable(typeof(System.Text.Json.Nodes.JsonArray))]
  internal partial class GenAIJsonContext : JsonSerializerContext
  {
  }
}
