//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Environments
{
    using Google.GenAI.Gaos.Models.Environments;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CreateEnvironmentRequestNetworkUnionType
    {
        private CreateEnvironmentRequestNetworkUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static CreateEnvironmentRequestNetworkUnionType EnvironmentNetworkEgressAllowlist
        {
            get {
                return new CreateEnvironmentRequestNetworkUnionType("EnvironmentNetworkEgressAllowlist");
            }
        }

        public static CreateEnvironmentRequestNetworkUnionType CreateEnvironmentRequestNetworkEnum
        {
            get {
                return new CreateEnvironmentRequestNetworkUnionType("CreateEnvironmentRequest_network_enum");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(CreateEnvironmentRequestNetworkUnionType v)
        {
            return v.Value;
        }
        public static CreateEnvironmentRequestNetworkUnionType FromString(string v)
        {
            switch (v)
            {
                case "EnvironmentNetworkEgressAllowlist":
                    return EnvironmentNetworkEgressAllowlist;
                case "CreateEnvironmentRequest_network_enum":
                    return CreateEnvironmentRequestNetworkEnum;
                default:
                    throw new ArgumentException("Invalid value for CreateEnvironmentRequestNetworkUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateEnvironmentRequestNetworkUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Network configuration for the environment.
    /// </summary>
    [JsonConverter(typeof(CreateEnvironmentRequestNetworkUnion.CreateEnvironmentRequestNetworkUnionConverter))]
    public class CreateEnvironmentRequestNetworkUnion
    {
        public CreateEnvironmentRequestNetworkUnion(CreateEnvironmentRequestNetworkUnionType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public EnvironmentNetworkEgressAllowlist? EnvironmentNetworkEgressAllowlist { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public CreateEnvironmentRequestNetworkEnum? CreateEnvironmentRequestNetworkEnum { get; set; }

        public CreateEnvironmentRequestNetworkUnionType Type { get; set; }
        public static CreateEnvironmentRequestNetworkUnion CreateEnvironmentNetworkEgressAllowlist(EnvironmentNetworkEgressAllowlist environmentNetworkEgressAllowlist)
        {
            CreateEnvironmentRequestNetworkUnionType typ = CreateEnvironmentRequestNetworkUnionType.EnvironmentNetworkEgressAllowlist;

            CreateEnvironmentRequestNetworkUnion res = new CreateEnvironmentRequestNetworkUnion(typ);
            res.EnvironmentNetworkEgressAllowlist = environmentNetworkEgressAllowlist;
            return res;
        }
        public static CreateEnvironmentRequestNetworkUnion CreateCreateEnvironmentRequestNetworkEnum(CreateEnvironmentRequestNetworkEnum createEnvironmentRequestNetworkEnum)
        {
            CreateEnvironmentRequestNetworkUnionType typ = CreateEnvironmentRequestNetworkUnionType.CreateEnvironmentRequestNetworkEnum;

            CreateEnvironmentRequestNetworkUnion res = new CreateEnvironmentRequestNetworkUnion(typ);
            res.CreateEnvironmentRequestNetworkEnum = createEnvironmentRequestNetworkEnum;
            return res;
        }

        public class CreateEnvironmentRequestNetworkUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateEnvironmentRequestNetworkUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {

                    throw new JsonSerializationException("Received unexpected null JSON value");
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<CreateEnvironmentRequestNetworkUnionType>();
                unionCandidates.Add<EnvironmentNetworkEgressAllowlist>("EnvironmentNetworkEgressAllowlist", 0, CreateEnvironmentRequestNetworkUnionType.EnvironmentNetworkEgressAllowlist);
                unionCandidates.Add<CreateEnvironmentRequestNetworkEnum>("CreateEnvironmentRequestNetworkEnum", 1, CreateEnvironmentRequestNetworkUnionType.CreateEnvironmentRequestNetworkEnum);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    throw new ResponseBodyDeserializer.DeserializationException(typeof(CreateEnvironmentRequestNetworkUnion));
                }

                var result = new CreateEnvironmentRequestNetworkUnion(winner.TypeName);
                typeof(CreateEnvironmentRequestNetworkUnion).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CreateEnvironmentRequestNetworkUnion res = (CreateEnvironmentRequestNetworkUnion)value;

                if (res.EnvironmentNetworkEgressAllowlist != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.EnvironmentNetworkEgressAllowlist));
                    return;
                }

                if (res.CreateEnvironmentRequestNetworkEnum != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CreateEnvironmentRequestNetworkEnum));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}