// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Environments
{
    using Google.GenAI.Gaos.Models.Environments;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Metadata for a file or directory within an environment.
    /// </summary>
    public class EnvironmentFile
    {
        /// <summary>
        /// Output only. The creation time of the file/directory.
        /// </summary>
        [JsonProperty("created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// Output only. The MIME type of the file (e.g., "text/python", "image/png").<br/>
        /// Empty for directories.<br/>
        /// NOLINT.
        /// </summary>
        [JsonProperty("mime_type")]
        public string? MimeType { get; set; }

        /// <summary>
        /// Output only. The modification time of the file/directory.
        /// </summary>
        [JsonProperty("modified")]
        public DateTime? Modified { get; set; }

        /// <summary>
        /// Output only. The name of the file or directory (e.g., "main.py" or "src").
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Output only. The full relative path within the environment<br/>
        /// (e.g., "workspace/src/main.py").
        /// </summary>
        [JsonProperty("path")]
        public string? Path { get; set; }

        /// <summary>
        /// Output only. The size of the file/directory in bytes.<br/>
        /// NOLINT.
        /// </summary>
        [JsonProperty("size_bytes")]
        public string? SizeBytes { get; set; }

        /// <summary>
        /// Output only. The type of the entry.
        /// </summary>
        [JsonProperty("type")]
        public Models.Environments.Type? Type { get; set; }
    }
}