//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Environments
{
    using Google.GenAI.Gaos.Models.Components;
    using Google.GenAI.Gaos.Models.Environments;
    using Google.GenAI.Gaos.Models.Interactions;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// An execution environment for an agent.
    /// </summary>
    public class Environment
    {
        /// <summary>
        /// Output only. The time at which the environment was created in ISO 8601 format<br/>
        /// (YYYY-MM-DDThh:mm:ssZ).
        /// </summary>
        [JsonProperty("created", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Created { get; set; }

        /// <summary>
        /// Output only. The number of files in the environment, output only.
        /// </summary>
        [JsonProperty("file_count", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? FileCount { get; set; }

        /// <summary>
        /// Required. Output only. The ID of the environment.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Output only. The time at which the environment was last accessed in ISO 8601 format<br/>
        /// (YYYY-MM-DDThh:mm:ssZ).
        /// </summary>
        [JsonProperty("last_accessed", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? LastAccessed { get; set; }

        /// <summary>
        /// Network configuration for the environment.
        /// </summary>
        [JsonProperty("network", Required = Newtonsoft.Json.Required.DisallowNull)]
        public EnvironmentNetworkUnion? Network { get; set; }

        /// <summary>
        /// Output only. The total size of the environment files in bytes, output only.
        /// </summary>
        [JsonProperty("size_bytes", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? SizeBytes { get; set; }

        /// <summary>
        /// Sources to be mounted into the environment.
        /// </summary>
        [JsonProperty("sources", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<Source>? Sources { get; set; }

        /// <summary>
        /// Output only. The status of the environment container.
        /// </summary>
        [JsonProperty("status", Required = Newtonsoft.Json.Required.DisallowNull)]
        public Models.Environments.Status? Status { get; set; }

        /// <summary>
        /// Output only. The time at which the environment was last updated in ISO 8601 format<br/>
        /// (YYYY-MM-DDThh:mm:ssZ).
        /// </summary>
        [JsonProperty("updated", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Updated { get; set; }
    }
}