//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Webhooks
{
    using Google.GenAI.Gaos.Utils;

    /// <summary>
    /// Request message for WebhookService.PingWebhook.
    /// </summary>
    public class PingWebhookRequest
    {
    }
}