// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Webhooks
{
    using Google.GenAI.Gaos.Models.Webhooks;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class WebhookUpdate
    {
        /// <summary>
        /// Optional. The user-provided name of the webhook.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Optional. The URI to which webhook events will be sent.
        /// </summary>
        [JsonProperty("uri")]
        public string? Uri { get; set; }

        /// <summary>
        /// Optional. The events that the webhook is subscribed to.<br/>
        /// Available events:<br/>
        /// - batch.succeeded<br/>
        /// - batch.expired<br/>
        /// - batch.failed<br/>
        /// - interaction.requires_action<br/>
        /// - interaction.completed<br/>
        /// - interaction.failed<br/>
        /// - video.generated.
        /// </summary>
        [JsonProperty("subscribed_events")]
        public List<WebhookUpdateSubscribedEvent>? SubscribedEvents { get; set; }

        /// <summary>
        /// Optional. The state of the webhook.
        /// </summary>
        [JsonProperty("state")]
        public WebhookUpdateState? State { get; set; }
    }
}