//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Webhooks
{
    using Google.GenAI.Gaos.Models.Webhooks;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Response message for WebhookService.ListWebhooks.
    /// </summary>
    public class WebhookListResponse
    {
        /// <summary>
        /// A token, which can be sent as `page_token` to retrieve the next page.<br/>
        /// If this field is omitted, there are no subsequent pages.
        /// </summary>
        [JsonProperty("next_page_token", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? NextPageToken { get; set; }

        /// <summary>
        /// The webhooks.
        /// </summary>
        [JsonProperty("webhooks", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<Webhook>? Webhooks { get; set; }
    }
}