//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Webhooks
{
    using Google.GenAI.Gaos.Models.Webhooks;
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A Webhook resource.
    /// </summary>
    public class Webhook
    {
        /// <summary>
        /// Output only. The timestamp when the webhook was created.
        /// </summary>
        [JsonProperty("create_time", Required = Newtonsoft.Json.Required.DisallowNull)]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// Output only. The ID of the webhook.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Id { get; set; }

        /// <summary>
        /// Optional. The user-provided name of the webhook.
        /// </summary>
        [JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Name { get; set; }

        /// <summary>
        /// Output only. The new signing secret for the webhook. Only populated on create.
        /// </summary>
        [JsonProperty("new_signing_secret", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? NewSigningSecret { get; set; }

        /// <summary>
        /// Output only. The signing secrets associated with this webhook.
        /// </summary>
        [JsonProperty("signing_secrets", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<SigningSecret>? SigningSecrets { get; set; }

        /// <summary>
        /// Output only. The state of the webhook.
        /// </summary>
        [JsonProperty("state", Required = Newtonsoft.Json.Required.DisallowNull)]
        public WebhookState? State { get; set; }

        /// <summary>
        /// Required. The events that the webhook is subscribed to.<br/>
        /// Available events:<br/>
        /// - batch.succeeded<br/>
        /// - batch.expired<br/>
        /// - batch.failed<br/>
        /// - interaction.requires_action<br/>
        /// - interaction.completed<br/>
        /// - interaction.failed<br/>
        /// - video.generated.
        /// </summary>
        [JsonProperty("subscribed_events", Required = Newtonsoft.Json.Required.Always)]
        public List<WebhookSubscribedEvent> SubscribedEvents { get; set; } = default!;

        /// <summary>
        /// Output only. The timestamp when the webhook was last updated.
        /// </summary>
        [JsonProperty("update_time", Required = Newtonsoft.Json.Required.DisallowNull)]
        public DateTime? UpdateTime { get; set; }

        /// <summary>
        /// Required. The URI to which webhook events will be sent.
        /// </summary>
        [JsonProperty("uri", Required = Newtonsoft.Json.Required.Always)]
        public string Uri { get; set; } = default!;
    }
}