//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Webhooks
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Optional. The state of the webhook.
    /// </summary>
    public enum WebhookUpdateState
    {
        [JsonProperty("enabled")] Enabled,
        [JsonProperty("disabled")] Disabled,
        [JsonProperty("disabled_due_to_failed_deliveries")] DisabledDueToFailedDeliveries,
    }

    public static class WebhookUpdateStateExtension
    {
        public static string Value(this WebhookUpdateState value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static WebhookUpdateState ToEnum(this string value)
        {
            foreach (var field in typeof(WebhookUpdateState).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is WebhookUpdateState)
                    {
                        return (WebhookUpdateState)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum WebhookUpdateState");
        }
    }
}