// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Google.GenAI.Gaos.Models.Components
{
    using Google.GenAI.Gaos.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class Security
    {
        /// <summary>
        /// Gemini API key sent as x-goog-api-key.
        /// </summary>
        [JsonProperty("apiKey")]
        [SpeakeasyMetadata("security:scheme=true,type=http,subType=custom,name=apiKey")]
        public string? ApiKey { get; set; }

        /// <summary>
        /// OAuth access token sent as a bearer Authorization header.
        /// </summary>
        [JsonProperty("accessToken")]
        [SpeakeasyMetadata("security:scheme=true,type=http,subType=custom,name=accessToken")]
        public string? AccessToken { get; set; }

        /// <summary>
        /// Additional default headers to apply before request-specific headers and auth.
        /// </summary>
        [JsonProperty("defaultHeaders")]
        [SpeakeasyMetadata("security:scheme=true,type=http,subType=custom,name=defaultHeaders")]
        public Dictionary<string, string>? DefaultHeaders { get; set; }
    }
}