name: Build and Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false

      - name: Setup .NET ⚙️
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: '8.0.x' # Use the .NET version your project uses

      - name: Install DocFX 🛠️
        run: dotnet tool update -g docfx

      - name: Create index.md from README.md
        run: cp README.md index.md

      - name: Generate DocFx metadata
        run: docfx metadata docfx.json

      - name: Build Documentation 📖
        run: docfx build docfx.json

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
