name: Publish NuGet Package

on:
  push:
    tags:
      - 'Google.GenAI-v*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet restore Google.GenAI/Google.GenAI.csproj

      - name: Build
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet build Google.GenAI/Google.GenAI.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet pack Google.GenAI/Google.GenAI.csproj --configuration Release --no-build --output ./nuget

      - name: Publish to NuGet
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet nuget push "./nuget/Google.GenAI.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
