name: Publish NuGet Package

on:
  push:
    tags:
      - 'Google.GenAI-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet restore Google.GenAI/Google.GenAI.csproj

      - name: Build
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet build Google.GenAI/Google.GenAI.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet pack Google.GenAI/Google.GenAI.csproj --configuration Release --no-build --output ./nuget

      - name: NuGet login (OIDC → temp API key)
        if: github.repository == 'googleapis/dotnet-genai'
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }} # configured in nuget.org, do not hardcode

      - name: Publish to NuGet
        if: github.repository == 'googleapis/dotnet-genai'
        run: dotnet nuget push "./nuget/Google.GenAI.*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json